-- 10級（小学1年相当）漢字マスタ 80字
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('一', 10, 'イチ', 'ひと(つ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('右', 10, 'ウ・ユウ', 'みぎ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('雨', 10, 'ウ', 'あめ・あま', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('円', 10, 'エン', 'まる(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('王', 10, 'オウ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('音', 10, 'オン・イン', 'おと・ね', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('下', 10, 'カ・ゲ', 'した・しも・くだ(る)・さ(げる)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('火', 10, 'カ', 'ひ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('花', 10, 'カ', 'はな', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('貝', 10, '', 'かい', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('学', 10, 'ガク', 'まな(ぶ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('気', 10, 'キ・ケ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('九', 10, 'キュウ・ク', 'ここの(つ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('休', 10, 'キュウ', 'やす(む)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('玉', 10, 'ギョク', 'たま', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('金', 10, 'キン・コン', 'かね', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('空', 10, 'クウ', 'そら・あ(く)・から', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('月', 10, 'ゲツ・ガツ', 'つき', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('犬', 10, 'ケン', 'いぬ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('見', 10, 'ケン', 'み(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('五', 10, 'ゴ', 'いつ(つ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('口', 10, 'コウ', 'くち', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('校', 10, 'コウ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('左', 10, 'サ', 'ひだり', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('三', 10, 'サン', 'み(つ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('山', 10, 'サン', 'やま', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('子', 10, 'シ・ス', 'こ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('四', 10, 'シ', 'よ・よ(つ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('糸', 10, 'シ', 'いと', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('字', 10, 'ジ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('耳', 10, 'ジ', 'みみ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('七', 10, 'シチ', 'なな(つ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('車', 10, 'シャ', 'くるま', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('手', 10, 'シュ', 'て', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('十', 10, 'ジュウ', 'とお・と', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('出', 10, 'シュツ', 'で(る)・だ(す)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('女', 10, 'ジョ・ニョ', 'おんな', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('小', 10, 'ショウ', 'ちい(さい)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('上', 10, 'ジョウ', 'うえ・あ(げる)・のぼ(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('森', 10, 'シン', 'もり', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('人', 10, 'ジン・ニン', 'ひと', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('水', 10, 'スイ', 'みず', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('正', 10, 'セイ・ショウ', 'ただ(しい)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('生', 10, 'セイ・ショウ', 'い(きる)・う(まれる)・なま', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('青', 10, 'セイ', 'あお', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('夕', 10, 'セキ', 'ゆう', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('石', 10, 'セキ・シャク', 'いし', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('赤', 10, 'セキ', 'あか', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('千', 10, 'セン', 'ち', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('川', 10, 'セン', 'かわ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('先', 10, 'セン', 'さき', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('早', 10, 'ソウ', 'はや(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('草', 10, 'ソウ', 'くさ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('足', 10, 'ソク', 'あし・た(りる)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('村', 10, 'ソン', 'むら', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('大', 10, 'ダイ・タイ', 'おお(きい)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('男', 10, 'ダン・ナン', 'おとこ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('竹', 10, 'チク', 'たけ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('中', 10, 'チュウ', 'なか', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('虫', 10, 'チュウ', 'むし', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('町', 10, 'チョウ', 'まち', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('天', 10, 'テン', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('田', 10, 'デン', 'た', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('土', 10, 'ド・ト', 'つち', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('二', 10, 'ニ', 'ふた(つ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('日', 10, 'ニチ・ジツ', 'ひ・か', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('入', 10, 'ニュウ', 'い(る)・はい(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('年', 10, 'ネン', 'とし', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('白', 10, 'ハク・ビャク', 'しろ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('八', 10, 'ハチ', 'や(つ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('百', 10, 'ヒャク', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('文', 10, 'ブン・モン', 'ふみ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('木', 10, 'モク・ボク', 'き', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('本', 10, 'ホン', 'もと', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('名', 10, 'メイ・ミョウ', 'な', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('目', 10, 'モク', 'め', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('立', 10, 'リツ', 'た(つ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('力', 10, 'リョク・リキ', 'ちから', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('林', 10, 'リン', 'はやし', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('六', 10, 'ロク', 'む(つ)', NULL, NULL, NULL);

-- 10級 読み問題（各漢字1問、4択）
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '一' AND level = 10), 'reading', '「一」の読み方として正しいものはどれですか？', 'ひと', '["おんな", "オウ", "ひと", "かね"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '右' AND level = 10), 'reading', '「右」の読み方として正しいものはどれですか？', 'みぎ', '["たま", "ヒャク", "みぎ", "ここの"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '雨' AND level = 10), 'reading', '「雨」の読み方として正しいものはどれですか？', 'あめ', '["ここの", "みみ", "いと", "あめ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '円' AND level = 10), 'reading', '「円」の読み方として正しいものはどれですか？', 'まる', '["まる", "ヒャク", "むら", "ジ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '王' AND level = 10), 'reading', '「王」の読み方として正しいものはどれですか？', 'オウ', '["おお", "オウ", "ひと", "くち"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '音' AND level = 10), 'reading', '「音」の読み方として正しいものはどれですか？', 'おと', '["あお", "たま", "いと", "おと"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '下' AND level = 10), 'reading', '「下」の読み方として正しいものはどれですか？', 'した', '["はやし", "いし", "した", "ゆう"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '火' AND level = 10), 'reading', '「火」の読み方として正しいものはどれですか？', 'ひ', '["かわ", "ヒャク", "そら", "ひ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '花' AND level = 10), 'reading', '「花」の読み方として正しいものはどれですか？', 'はな', '["あか", "な", "やま", "はな"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '貝' AND level = 10), 'reading', '「貝」の読み方として正しいものはどれですか？', 'かい', '["みみ", "キ", "うえ", "かい"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '学' AND level = 10), 'reading', '「学」の読み方として正しいものはどれですか？', 'まな', '["くち", "まな", "むし", "あか"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '気' AND level = 10), 'reading', '「気」の読み方として正しいものはどれですか？', 'キ', '["はやし", "キ", "かい", "で"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '九' AND level = 10), 'reading', '「九」の読み方として正しいものはどれですか？', 'ここの', '["くち", "ここの", "かわ", "まち"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '休' AND level = 10), 'reading', '「休」の読み方として正しいものはどれですか？', 'やす', '["みみ", "ひ", "ただ", "やす"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '玉' AND level = 10), 'reading', '「玉」の読み方として正しいものはどれですか？', 'たま', '["いと", "で", "たま", "はな"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '金' AND level = 10), 'reading', '「金」の読み方として正しいものはどれですか？', 'かね', '["はや", "み", "かね", "むし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '空' AND level = 10), 'reading', '「空」の読み方として正しいものはどれですか？', 'そら', '["そら", "き", "や", "とお"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '月' AND level = 10), 'reading', '「月」の読み方として正しいものはどれですか？', 'つき', '["あか", "ジ", "つき", "いぬ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '犬' AND level = 10), 'reading', '「犬」の読み方として正しいものはどれですか？', 'いぬ', '["たま", "いぬ", "いつ", "くち"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '見' AND level = 10), 'reading', '「見」の読み方として正しいものはどれですか？', 'み', '["み", "はや", "さき", "はやし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '五' AND level = 10), 'reading', '「五」の読み方として正しいものはどれですか？', 'いつ', '["いつ", "ふみ", "たま", "みぎ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '口' AND level = 10), 'reading', '「口」の読み方として正しいものはどれですか？', 'くち', '["うえ", "くち", "おとこ", "たま"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '校' AND level = 10), 'reading', '「校」の読み方として正しいものはどれですか？', 'コウ', '["ひだり", "とお", "ひ", "コウ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '左' AND level = 10), 'reading', '「左」の読み方として正しいものはどれですか？', 'ひだり', '["はやし", "ひだり", "こ", "ひ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '三' AND level = 10), 'reading', '「三」の読み方として正しいものはどれですか？', 'み', '["ひと", "み", "ふみ", "や"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '山' AND level = 10), 'reading', '「山」の読み方として正しいものはどれですか？', 'やま', '["ひと", "あか", "やま", "たま"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '子' AND level = 10), 'reading', '「子」の読み方として正しいものはどれですか？', 'こ', '["もと", "つち", "まな", "こ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '四' AND level = 10), 'reading', '「四」の読み方として正しいものはどれですか？', 'よ', '["よ", "テン", "ふみ", "そら"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '糸' AND level = 10), 'reading', '「糸」の読み方として正しいものはどれですか？', 'いと', '["いと", "やま", "よ", "ヒャク"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '字' AND level = 10), 'reading', '「字」の読み方として正しいものはどれですか？', 'ジ', '["たけ", "とし", "なか", "ジ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '耳' AND level = 10), 'reading', '「耳」の読み方として正しいものはどれですか？', 'みみ', '["あめ", "みみ", "あお", "はな"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '七' AND level = 10), 'reading', '「七」の読み方として正しいものはどれですか？', 'なな', '["ひ", "かい", "なな", "ひと"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '車' AND level = 10), 'reading', '「車」の読み方として正しいものはどれですか？', 'くるま', '["くるま", "かい", "い", "い"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '手' AND level = 10), 'reading', '「手」の読み方として正しいものはどれですか？', 'て', '["ヒャク", "よ", "て", "そら"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '十' AND level = 10), 'reading', '「十」の読み方として正しいものはどれですか？', 'とお', '["ここの", "あし", "み", "とお"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '出' AND level = 10), 'reading', '「出」の読み方として正しいものはどれですか？', 'で', '["いし", "で", "おお", "あし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '女' AND level = 10), 'reading', '「女」の読み方として正しいものはどれですか？', 'おんな', '["ここの", "くさ", "おんな", "ひ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '小' AND level = 10), 'reading', '「小」の読み方として正しいものはどれですか？', 'ちい', '["や", "ちい", "なか", "み"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '上' AND level = 10), 'reading', '「上」の読み方として正しいものはどれですか？', 'うえ', '["まち", "なな", "で", "うえ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '森' AND level = 10), 'reading', '「森」の読み方として正しいものはどれですか？', 'もり', '["した", "ヒャク", "みぎ", "もり"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '人' AND level = 10), 'reading', '「人」の読み方として正しいものはどれですか？', 'ひと', '["ふた", "ひと", "つち", "むら"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '水' AND level = 10), 'reading', '「水」の読み方として正しいものはどれですか？', 'みず', '["みず", "かわ", "くち", "ひと"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '正' AND level = 10), 'reading', '「正」の読み方として正しいものはどれですか？', 'ただ', '["おんな", "おお", "ただ", "き"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '生' AND level = 10), 'reading', '「生」の読み方として正しいものはどれですか？', 'い', '["ひ", "ちい", "よ", "い"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '青' AND level = 10), 'reading', '「青」の読み方として正しいものはどれですか？', 'あお', '["ひ", "あお", "した", "め"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '夕' AND level = 10), 'reading', '「夕」の読み方として正しいものはどれですか？', 'ゆう', '["まな", "い", "ゆう", "ひ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '石' AND level = 10), 'reading', '「石」の読み方として正しいものはどれですか？', 'いし', '["かね", "いし", "くさ", "みみ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '赤' AND level = 10), 'reading', '「赤」の読み方として正しいものはどれですか？', 'あか', '["め", "あか", "まな", "むら"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '千' AND level = 10), 'reading', '「千」の読み方として正しいものはどれですか？', 'ち', '["みみ", "ひと", "ち", "て"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '川' AND level = 10), 'reading', '「川」の読み方として正しいものはどれですか？', 'かわ', '["ひと", "かい", "むし", "かわ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '先' AND level = 10), 'reading', '「先」の読み方として正しいものはどれですか？', 'さき', '["よ", "かい", "さき", "や"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '早' AND level = 10), 'reading', '「早」の読み方として正しいものはどれですか？', 'はや', '["あか", "はな", "はや", "なな"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '草' AND level = 10), 'reading', '「草」の読み方として正しいものはどれですか？', 'くさ', '["む", "ヒャク", "うえ", "くさ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '足' AND level = 10), 'reading', '「足」の読み方として正しいものはどれですか？', 'あし', '["やす", "つき", "て", "あし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '村' AND level = 10), 'reading', '「村」の読み方として正しいものはどれですか？', 'むら', '["むら", "はやし", "おんな", "とお"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '大' AND level = 10), 'reading', '「大」の読み方として正しいものはどれですか？', 'おお', '["て", "おお", "こ", "ひ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '男' AND level = 10), 'reading', '「男」の読み方として正しいものはどれですか？', 'おとこ', '["むら", "キ", "で", "おとこ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '竹' AND level = 10), 'reading', '「竹」の読み方として正しいものはどれですか？', 'たけ', '["たけ", "そら", "て", "いつ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '中' AND level = 10), 'reading', '「中」の読み方として正しいものはどれですか？', 'なか', '["き", "たま", "みぎ", "なか"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '虫' AND level = 10), 'reading', '「虫」の読み方として正しいものはどれですか？', 'むし', '["オウ", "むし", "あか", "ヒャク"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '町' AND level = 10), 'reading', '「町」の読み方として正しいものはどれですか？', 'まち', '["もり", "いし", "おと", "まち"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '天' AND level = 10), 'reading', '「天」の読み方として正しいものはどれですか？', 'テン', '["なな", "テン", "やす", "ゆう"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '田' AND level = 10), 'reading', '「田」の読み方として正しいものはどれですか？', 'た', '["みみ", "いつ", "た", "コウ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '土' AND level = 10), 'reading', '「土」の読み方として正しいものはどれですか？', 'つち', '["ただ", "なな", "つち", "くさ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '二' AND level = 10), 'reading', '「二」の読み方として正しいものはどれですか？', 'ふた', '["オウ", "まち", "ふた", "ち"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '日' AND level = 10), 'reading', '「日」の読み方として正しいものはどれですか？', 'ひ', '["みみ", "ひと", "ひ", "ゆう"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '入' AND level = 10), 'reading', '「入」の読み方として正しいものはどれですか？', 'い', '["で", "ただ", "くさ", "い"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '年' AND level = 10), 'reading', '「年」の読み方として正しいものはどれですか？', 'とし', '["ひ", "や", "とし", "はや"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '白' AND level = 10), 'reading', '「白」の読み方として正しいものはどれですか？', 'しろ', '["て", "め", "しろ", "コウ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '八' AND level = 10), 'reading', '「八」の読み方として正しいものはどれですか？', 'や', '["あお", "や", "ちから", "おお"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '百' AND level = 10), 'reading', '「百」の読み方として正しいものはどれですか？', 'ヒャク', '["み", "かわ", "ヒャク", "な"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '文' AND level = 10), 'reading', '「文」の読み方として正しいものはどれですか？', 'ふみ', '["ふみ", "い", "しろ", "ひと"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '木' AND level = 10), 'reading', '「木」の読み方として正しいものはどれですか？', 'き', '["ひと", "はな", "ただ", "き"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '本' AND level = 10), 'reading', '「本」の読み方として正しいものはどれですか？', 'もと', '["もと", "くさ", "ふた", "もり"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '名' AND level = 10), 'reading', '「名」の読み方として正しいものはどれですか？', 'な', '["な", "ヒャク", "そら", "み"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '目' AND level = 10), 'reading', '「目」の読み方として正しいものはどれですか？', 'め', '["き", "め", "コウ", "む"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '立' AND level = 10), 'reading', '「立」の読み方として正しいものはどれですか？', 'た', '["た", "うえ", "おんな", "こ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '力' AND level = 10), 'reading', '「力」の読み方として正しいものはどれですか？', 'ちから', '["むし", "ちから", "おとこ", "よ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '林' AND level = 10), 'reading', '「林」の読み方として正しいものはどれですか？', 'はやし', '["まな", "ひ", "はやし", "おんな"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '六' AND level = 10), 'reading', '「六」の読み方として正しいものはどれですか？', 'む', '["やま", "いと", "む", "もり"]');
