-- 8級（小学3年相当）漢字マスタ 200字
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('悪', 8, 'アク・オ', 'わる(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('安', 8, 'アン', 'やす(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('暗', 8, 'アン', 'くら(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('医', 8, 'イ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('委', 8, 'イ', 'ゆだ(ねる)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('意', 8, 'イ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('育', 8, 'イク', 'そだ(つ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('員', 8, 'イン', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('院', 8, 'イン', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('飲', 8, 'イン', 'の(む)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('運', 8, 'ウン', 'はこ(ぶ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('泳', 8, 'エイ', 'およ(ぐ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('駅', 8, 'エキ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('央', 8, 'オウ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('横', 8, 'オウ', 'よこ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('屋', 8, 'オク', 'や', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('温', 8, 'オン', 'あたた(かい)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('化', 8, 'カ・ケ', 'ば(ける)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('荷', 8, 'カ', 'に', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('界', 8, 'カイ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('開', 8, 'カイ', 'ひら(く)・あ(ける)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('階', 8, 'カイ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('寒', 8, 'カン', 'さむ(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('感', 8, 'カン', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('漢', 8, 'カン', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('館', 8, 'カン', 'やかた', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('岸', 8, 'ガン', 'きし', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('起', 8, 'キ', 'お(きる)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('期', 8, 'キ・ゴ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('客', 8, 'キャク・カク', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('究', 8, 'キュウ', 'きわ(める)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('急', 8, 'キュウ', 'いそ(ぐ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('級', 8, 'キュウ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('宮', 8, 'キュウ・グウ', 'みや', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('球', 8, 'キュウ', 'たま', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('去', 8, 'キョ・コ', 'さ(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('橋', 8, 'キョウ', 'はし', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('業', 8, 'ギョウ・ゴウ', 'わざ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('曲', 8, 'キョク', 'ま(がる)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('局', 8, 'キョク', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('銀', 8, 'ギン', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('区', 8, 'ク', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('苦', 8, 'ク', 'くる(しい)・にが(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('具', 8, 'グ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('君', 8, 'クン', 'きみ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('係', 8, 'ケイ', 'かかり・かか(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('軽', 8, 'ケイ', 'かる(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('血', 8, 'ケツ', 'ち', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('決', 8, 'ケツ', 'き(める)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('研', 8, 'ケン', 'と(ぐ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('県', 8, 'ケン', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('庫', 8, 'コ・ク', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('湖', 8, 'コ', 'みずうみ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('向', 8, 'コウ', 'む(く)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('幸', 8, 'コウ', 'しあわ(せ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('港', 8, 'コウ', 'みなと', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('号', 8, 'ゴウ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('根', 8, 'コン', 'ね', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('祭', 8, 'サイ', 'まつ(り)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('皿', 8, 'サラ', 'さら', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('仕', 8, 'シ・ジ', 'つか(える)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('死', 8, 'シ', 'し(ぬ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('使', 8, 'シ', 'つか(う)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('始', 8, 'シ', 'はじ(める)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('指', 8, 'シ', 'ゆび・さ(す)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('歯', 8, 'シ', 'は', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('詩', 8, 'シ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('次', 8, 'ジ・シ', 'つぎ・つ(ぐ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('事', 8, 'ジ', 'こと', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('持', 8, 'ジ', 'も(つ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('式', 8, 'シキ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('実', 8, 'ジツ', 'み・みの(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('写', 8, 'シャ', 'うつ(す)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('者', 8, 'シャ', 'もの', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('主', 8, 'シュ・ス', 'ぬし・おも', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('守', 8, 'シュ・ス', 'まも(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('取', 8, 'シュ', 'と(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('酒', 8, 'シュ', 'さけ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('受', 8, 'ジュ', 'う(ける)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('州', 8, 'シュウ', 'す', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('拾', 8, 'シュウ', 'ひろ(う)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('終', 8, 'シュウ', 'お(わる)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('習', 8, 'シュウ', 'なら(う)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('集', 8, 'シュウ', 'あつ(まる)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('住', 8, 'ジュウ', 'す(む)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('重', 8, 'ジュウ・チョウ', 'おも(い)・かさ(ねる)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('宿', 8, 'シュク', 'やど', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('所', 8, 'ショ', 'ところ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('暑', 8, 'ショ', 'あつ(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('助', 8, 'ジョ', 'たす(ける)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('昭', 8, 'ショウ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('消', 8, 'ショウ', 'き(える)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('商', 8, 'ショウ', 'あきな(う)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('章', 8, 'ショウ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('勝', 8, 'ショウ', 'か(つ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('乗', 8, 'ジョウ', 'の(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('植', 8, 'ショク', 'う(える)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('申', 8, 'シン', 'もう(す)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('身', 8, 'シン', 'み', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('神', 8, 'シン・ジン', 'かみ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('真', 8, 'シン', 'ま', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('深', 8, 'シン', 'ふか(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('進', 8, 'シン', 'すす(む)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('世', 8, 'セイ・セ', 'よ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('整', 8, 'セイ', 'ととの(える)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('昔', 8, 'セキ', 'むかし', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('全', 8, 'ゼン', 'まった(く)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('相', 8, 'ソウ・ショウ', 'あい', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('送', 8, 'ソウ', 'おく(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('想', 8, 'ソウ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('息', 8, 'ソク', 'いき', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('速', 8, 'ソク', 'はや(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('族', 8, 'ゾク', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('他', 8, 'タ', 'ほか', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('打', 8, 'ダ', 'う(つ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('対', 8, 'タイ・ツイ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('待', 8, 'タイ', 'ま(つ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('代', 8, 'ダイ・タイ', 'か(わる)・よ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('第', 8, 'ダイ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('題', 8, 'ダイ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('炭', 8, 'タン', 'すみ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('短', 8, 'タン', 'みじか(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('談', 8, 'ダン', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('着', 8, 'チャク', 'き(る)・つ(く)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('注', 8, 'チュウ', 'そそ(ぐ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('柱', 8, 'チュウ', 'はしら', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('丁', 8, 'チョウ・テイ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('帳', 8, 'チョウ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('調', 8, 'チョウ', 'しら(べる)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('追', 8, 'ツイ', 'お(う)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('定', 8, 'テイ・ジョウ', 'さだ(める)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('庭', 8, 'テイ', 'にわ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('笛', 8, 'テキ', 'ふえ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('鉄', 8, 'テツ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('転', 8, 'テン', 'ころ(がる)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('都', 8, 'ト・ツ', 'みやこ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('度', 8, 'ド・ト', 'たび', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('投', 8, 'トウ', 'な(げる)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('豆', 8, 'トウ・ズ', 'まめ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('島', 8, 'トウ', 'しま', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('湯', 8, 'トウ', 'ゆ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('登', 8, 'トウ・ト', 'のぼ(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('等', 8, 'トウ', 'ひと(しい)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('動', 8, 'ドウ', 'うご(く)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('童', 8, 'ドウ', 'わらべ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('農', 8, 'ノウ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('波', 8, 'ハ', 'なみ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('配', 8, 'ハイ', 'くば(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('倍', 8, 'バイ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('箱', 8, '', 'はこ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('畑', 8, '', 'はたけ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('発', 8, 'ハツ・ホツ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('反', 8, 'ハン・ホン', 'そ(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('坂', 8, 'ハン', 'さか', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('板', 8, 'ハン・バン', 'いた', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('皮', 8, 'ヒ', 'かわ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('悲', 8, 'ヒ', 'かな(しい)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('美', 8, 'ビ', 'うつく(しい)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('鼻', 8, 'ビ', 'はな', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('筆', 8, 'ヒツ', 'ふで', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('氷', 8, 'ヒョウ', 'こおり', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('表', 8, 'ヒョウ', 'おもて・あらわ(す)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('秒', 8, 'ビョウ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('病', 8, 'ビョウ・ヘイ', 'やまい', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('品', 8, 'ヒン', 'しな', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('負', 8, 'フ', 'ま(ける)・お(う)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('部', 8, 'ブ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('服', 8, 'フク', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('福', 8, 'フク', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('物', 8, 'ブツ・モツ', 'もの', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('平', 8, 'ヘイ・ビョウ', 'たい(ら)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('返', 8, 'ヘン', 'かえ(す)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('勉', 8, 'ベン', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('放', 8, 'ホウ', 'はな(す)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('味', 8, 'ミ', 'あじ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('命', 8, 'メイ・ミョウ', 'いのち', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('面', 8, 'メン', 'おも・つら', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('問', 8, 'モン', 'と(う)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('役', 8, 'ヤク・エキ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('薬', 8, 'ヤク', 'くすり', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('由', 8, 'ユ・ユウ', 'よし', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('油', 8, 'ユ', 'あぶら', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('有', 8, 'ユウ・ウ', 'あ(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('遊', 8, 'ユウ', 'あそ(ぶ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('予', 8, 'ヨ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('羊', 8, 'ヨウ', 'ひつじ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('洋', 8, 'ヨウ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('葉', 8, 'ヨウ', 'は', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('陽', 8, 'ヨウ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('様', 8, 'ヨウ', 'さま', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('落', 8, 'ラク', 'お(ちる)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('流', 8, 'リュウ・ル', 'なが(れる)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('旅', 8, 'リョ', 'たび', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('両', 8, 'リョウ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('緑', 8, 'リョク・ロク', 'みどり', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('礼', 8, 'レイ・ライ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('列', 8, 'レツ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('練', 8, 'レン', 'ね(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('路', 8, 'ロ', 'じ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('和', 8, 'ワ', 'やわ(らぐ)', NULL, NULL, NULL);

-- 8級 読み問題（各漢字1問、4択）
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '悪' AND level = 8), 'reading', '「悪」の読み方として正しいものはどれですか？', 'わる', '["ころ", "むかし", "しま", "わる"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '安' AND level = 8), 'reading', '「安」の読み方として正しいものはどれですか？', 'やす', '["イン", "まも", "やす", "まつ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '暗' AND level = 8), 'reading', '「暗」の読み方として正しいものはどれですか？', 'くら', '["くら", "きし", "やわ", "ク"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '医' AND level = 8), 'reading', '「医」の読み方として正しいものはどれですか？', 'イ', '["じ", "イ", "さか", "むかし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '委' AND level = 8), 'reading', '「委」の読み方として正しいものはどれですか？', 'ゆだ', '["ふで", "もの", "ゆだ", "ところ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '意' AND level = 8), 'reading', '「意」の読み方として正しいものはどれですか？', 'イ', '["み", "そ", "イ", "きし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '育' AND level = 8), 'reading', '「育」の読み方として正しいものはどれですか？', 'そだ', '["かみ", "たす", "の", "そだ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '員' AND level = 8), 'reading', '「員」の読み方として正しいものはどれですか？', 'イン', '["こと", "さ", "イン", "ケン"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '院' AND level = 8), 'reading', '「院」の読み方として正しいものはどれですか？', 'イン', '["ほか", "あじ", "おも", "イン"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '飲' AND level = 8), 'reading', '「飲」の読み方として正しいものはどれですか？', 'の', '["う", "の", "ダン", "やまい"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '運' AND level = 8), 'reading', '「運」の読み方として正しいものはどれですか？', 'はこ', '["つか", "はこ", "か", "そそ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '泳' AND level = 8), 'reading', '「泳」の読み方として正しいものはどれですか？', 'およ', '["ク", "くら", "およ", "うつ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '駅' AND level = 8), 'reading', '「駅」の読み方として正しいものはどれですか？', 'エキ', '["ノウ", "あきな", "エキ", "コ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '央' AND level = 8), 'reading', '「央」の読み方として正しいものはどれですか？', 'オウ', '["キャク", "まつ", "あつ", "オウ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '横' AND level = 8), 'reading', '「横」の読み方として正しいものはどれですか？', 'よこ', '["あじ", "こおり", "ダン", "よこ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '屋' AND level = 8), 'reading', '「屋」の読み方として正しいものはどれですか？', 'や', '["ま", "や", "やす", "さま"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '温' AND level = 8), 'reading', '「温」の読み方として正しいものはどれですか？', 'あたた', '["ひら", "あたた", "シキ", "やす"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '化' AND level = 8), 'reading', '「化」の読み方として正しいものはどれですか？', 'ば', '["みやこ", "おもて", "ば", "と"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '荷' AND level = 8), 'reading', '「荷」の読み方として正しいものはどれですか？', 'に', '["に", "そそ", "あたた", "こと"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '界' AND level = 8), 'reading', '「界」の読み方として正しいものはどれですか？', 'カイ', '["カイ", "チョウ", "あたた", "ぬし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '開' AND level = 8), 'reading', '「開」の読み方として正しいものはどれですか？', 'ひら', '["ま", "のぼ", "う", "ひら"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '階' AND level = 8), 'reading', '「階」の読み方として正しいものはどれですか？', 'カイ', '["カイ", "たい", "さ", "ひら"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '寒' AND level = 8), 'reading', '「寒」の読み方として正しいものはどれですか？', 'さむ', '["さむ", "カイ", "み", "う"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '感' AND level = 8), 'reading', '「感」の読み方として正しいものはどれですか？', 'カン', '["カン", "あぶら", "イン", "ゆび"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '漢' AND level = 8), 'reading', '「漢」の読み方として正しいものはどれですか？', 'カン', '["に", "カン", "にわ", "み"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '館' AND level = 8), 'reading', '「館」の読み方として正しいものはどれですか？', 'やかた', '["やかた", "たま", "は", "ま"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '岸' AND level = 8), 'reading', '「岸」の読み方として正しいものはどれですか？', 'きし', '["なら", "きし", "たび", "キャク"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '起' AND level = 8), 'reading', '「起」の読み方として正しいものはどれですか？', 'お', '["お", "ひら", "やす", "むかし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '期' AND level = 8), 'reading', '「期」の読み方として正しいものはどれですか？', 'キ', '["ヤク", "キ", "ク", "ね"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '客' AND level = 8), 'reading', '「客」の読み方として正しいものはどれですか？', 'キャク', '["イ", "キャク", "ひろ", "やど"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '究' AND level = 8), 'reading', '「究」の読み方として正しいものはどれですか？', 'きわ', '["グ", "と", "ゆ", "きわ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '急' AND level = 8), 'reading', '「急」の読み方として正しいものはどれですか？', 'いそ', '["な", "カン", "ふか", "いそ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '級' AND level = 8), 'reading', '「級」の読み方として正しいものはどれですか？', 'キュウ', '["うつ", "キュウ", "みや", "ととの"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '宮' AND level = 8), 'reading', '「宮」の読み方として正しいものはどれですか？', 'みや', '["みや", "あつ", "そ", "しま"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '球' AND level = 8), 'reading', '「球」の読み方として正しいものはどれですか？', 'たま', '["ゆだ", "イン", "む", "たま"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '去' AND level = 8), 'reading', '「去」の読み方として正しいものはどれですか？', 'さ', '["カイ", "グ", "かかり", "さ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '橋' AND level = 8), 'reading', '「橋」の読み方として正しいものはどれですか？', 'はし', '["もう", "くすり", "はし", "シキ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '業' AND level = 8), 'reading', '「業」の読み方として正しいものはどれですか？', 'わざ', '["キョク", "さけ", "わざ", "こと"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '曲' AND level = 8), 'reading', '「曲」の読み方として正しいものはどれですか？', 'ま', '["ま", "かる", "はしら", "もの"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '局' AND level = 8), 'reading', '「局」の読み方として正しいものはどれですか？', 'キョク', '["キョク", "さけ", "もの", "と"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '銀' AND level = 8), 'reading', '「銀」の読み方として正しいものはどれですか？', 'ギン', '["そそ", "ギン", "キ", "ダイ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '区' AND level = 8), 'reading', '「区」の読み方として正しいものはどれですか？', 'ク', '["まつ", "ク", "き", "は"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '苦' AND level = 8), 'reading', '「苦」の読み方として正しいものはどれですか？', 'くる', '["まつ", "くる", "か", "ソウ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '具' AND level = 8), 'reading', '「具」の読み方として正しいものはどれですか？', 'グ', '["シキ", "まめ", "グ", "よし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '君' AND level = 8), 'reading', '「君」の読み方として正しいものはどれですか？', 'きみ', '["さら", "まめ", "う", "きみ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '係' AND level = 8), 'reading', '「係」の読み方として正しいものはどれですか？', 'かかり', '["かかり", "す", "かえ", "あじ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '軽' AND level = 8), 'reading', '「軽」の読み方として正しいものはどれですか？', 'かる', '["くば", "そ", "やす", "かる"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '血' AND level = 8), 'reading', '「血」の読み方として正しいものはどれですか？', 'ち', '["フク", "ち", "レイ", "ね"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '決' AND level = 8), 'reading', '「決」の読み方として正しいものはどれですか？', 'き', '["ショウ", "グ", "き", "や"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '研' AND level = 8), 'reading', '「研」の読み方として正しいものはどれですか？', 'と', '["と", "ま", "きわ", "お"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '県' AND level = 8), 'reading', '「県」の読み方として正しいものはどれですか？', 'ケン', '["つか", "たび", "や", "ケン"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '庫' AND level = 8), 'reading', '「庫」の読み方として正しいものはどれですか？', 'コ', '["コ", "オウ", "ひと", "ゆだ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '湖' AND level = 8), 'reading', '「湖」の読み方として正しいものはどれですか？', 'みずうみ', '["しま", "キ", "みずうみ", "おも"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '向' AND level = 8), 'reading', '「向」の読み方として正しいものはどれですか？', 'む', '["イン", "およ", "む", "くら"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '幸' AND level = 8), 'reading', '「幸」の読み方として正しいものはどれですか？', 'しあわ', '["しあわ", "やわ", "かわ", "キ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '港' AND level = 8), 'reading', '「港」の読み方として正しいものはどれですか？', 'みなと', '["ヤク", "みなと", "うご", "オウ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '号' AND level = 8), 'reading', '「号」の読み方として正しいものはどれですか？', 'ゴウ', '["カイ", "み", "な", "ゴウ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '根' AND level = 8), 'reading', '「根」の読み方として正しいものはどれですか？', 'ね', '["シ", "ね", "む", "カン"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '祭' AND level = 8), 'reading', '「祭」の読み方として正しいものはどれですか？', 'まつ', '["まめ", "まつ", "あつ", "カイ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '皿' AND level = 8), 'reading', '「皿」の読み方として正しいものはどれですか？', 'さら', '["おく", "やど", "ケン", "さら"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '仕' AND level = 8), 'reading', '「仕」の読み方として正しいものはどれですか？', 'つか', '["ととの", "さ", "つか", "イ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '死' AND level = 8), 'reading', '「死」の読み方として正しいものはどれですか？', 'し', '["し", "なみ", "と", "レイ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '使' AND level = 8), 'reading', '「使」の読み方として正しいものはどれですか？', 'つか', '["つか", "やど", "ソウ", "はこ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '始' AND level = 8), 'reading', '「始」の読み方として正しいものはどれですか？', 'はじ', '["はじ", "やまい", "まめ", "ひと"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '指' AND level = 8), 'reading', '「指」の読み方として正しいものはどれですか？', 'ゆび', '["ギン", "ゆび", "はこ", "そそ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '歯' AND level = 8), 'reading', '「歯」の読み方として正しいものはどれですか？', 'は', '["うつ", "は", "し", "す"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '詩' AND level = 8), 'reading', '「詩」の読み方として正しいものはどれですか？', 'シ', '["イ", "か", "はな", "シ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '次' AND level = 8), 'reading', '「次」の読み方として正しいものはどれですか？', 'つぎ', '["し", "つぎ", "たび", "ひろ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '事' AND level = 8), 'reading', '「事」の読み方として正しいものはどれですか？', 'こと', '["イ", "やす", "み", "こと"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '持' AND level = 8), 'reading', '「持」の読み方として正しいものはどれですか？', 'も', '["し", "も", "うつく", "わらべ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '式' AND level = 8), 'reading', '「式」の読み方として正しいものはどれですか？', 'シキ', '["なみ", "はしら", "シキ", "う"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '実' AND level = 8), 'reading', '「実」の読み方として正しいものはどれですか？', 'み', '["しな", "み", "う", "ひと"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '写' AND level = 8), 'reading', '「写」の読み方として正しいものはどれですか？', 'うつ', '["も", "う", "カイ", "うつ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '者' AND level = 8), 'reading', '「者」の読み方として正しいものはどれですか？', 'もの', '["もの", "ころ", "イ", "みどり"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '主' AND level = 8), 'reading', '「主」の読み方として正しいものはどれですか？', 'ぬし', '["あじ", "ショウ", "ギン", "ぬし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '守' AND level = 8), 'reading', '「守」の読み方として正しいものはどれですか？', 'まも', '["は", "チョウ", "まも", "ブ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '取' AND level = 8), 'reading', '「取」の読み方として正しいものはどれですか？', 'と', '["と", "わる", "のぼ", "ば"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '酒' AND level = 8), 'reading', '「酒」の読み方として正しいものはどれですか？', 'さけ', '["さけ", "くら", "ち", "きし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '受' AND level = 8), 'reading', '「受」の読み方として正しいものはどれですか？', 'う', '["す", "き", "イン", "う"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '州' AND level = 8), 'reading', '「州」の読み方として正しいものはどれですか？', 'す', '["ゾク", "す", "いき", "うつ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '拾' AND level = 8), 'reading', '「拾」の読み方として正しいものはどれですか？', 'ひろ', '["イ", "まった", "ひろ", "と"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '終' AND level = 8), 'reading', '「終」の読み方として正しいものはどれですか？', 'お', '["ま", "テツ", "お", "かみ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '習' AND level = 8), 'reading', '「習」の読み方として正しいものはどれですか？', 'なら', '["の", "あぶら", "ま", "なら"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '集' AND level = 8), 'reading', '「集」の読み方として正しいものはどれですか？', 'あつ', '["あつ", "ヨウ", "はしら", "ころ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '住' AND level = 8), 'reading', '「住」の読み方として正しいものはどれですか？', 'す', '["はこ", "す", "エキ", "し"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '重' AND level = 8), 'reading', '「重」の読み方として正しいものはどれですか？', 'おも', '["ふえ", "はや", "ヤク", "おも"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '宿' AND level = 8), 'reading', '「宿」の読み方として正しいものはどれですか？', 'やど', '["かえ", "ふで", "か", "やど"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '所' AND level = 8), 'reading', '「所」の読み方として正しいものはどれですか？', 'ところ', '["オウ", "ところ", "ふえ", "きわ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '暑' AND level = 8), 'reading', '「暑」の読み方として正しいものはどれですか？', 'あつ', '["エキ", "くすり", "カン", "あつ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '助' AND level = 8), 'reading', '「助」の読み方として正しいものはどれですか？', 'たす', '["ビョウ", "は", "みや", "たす"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '昭' AND level = 8), 'reading', '「昭」の読み方として正しいものはどれですか？', 'ショウ', '["よこ", "ケン", "ヨ", "ショウ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '消' AND level = 8), 'reading', '「消」の読み方として正しいものはどれですか？', 'き', '["ゆだ", "の", "き", "ゾク"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '商' AND level = 8), 'reading', '「商」の読み方として正しいものはどれですか？', 'あきな', '["あきな", "すみ", "まめ", "う"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '章' AND level = 8), 'reading', '「章」の読み方として正しいものはどれですか？', 'ショウ', '["あ", "フク", "みや", "ショウ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '勝' AND level = 8), 'reading', '「勝」の読み方として正しいものはどれですか？', 'か', '["か", "エキ", "し", "よ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '乗' AND level = 8), 'reading', '「乗」の読み方として正しいものはどれですか？', 'の', '["の", "おく", "き", "おも"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '植' AND level = 8), 'reading', '「植」の読み方として正しいものはどれですか？', 'う', '["レイ", "う", "ダン", "そだ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '申' AND level = 8), 'reading', '「申」の読み方として正しいものはどれですか？', 'もう', '["ひろ", "もう", "やど", "はし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '身' AND level = 8), 'reading', '「身」の読み方として正しいものはどれですか？', 'み', '["わらべ", "む", "カン", "み"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '神' AND level = 8), 'reading', '「神」の読み方として正しいものはどれですか？', 'かみ', '["ハツ", "ぬし", "かみ", "むかし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '真' AND level = 8), 'reading', '「真」の読み方として正しいものはどれですか？', 'ま', '["キュウ", "ま", "レイ", "カン"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '深' AND level = 8), 'reading', '「深」の読み方として正しいものはどれですか？', 'ふか', '["およ", "お", "わらべ", "ふか"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '進' AND level = 8), 'reading', '「進」の読み方として正しいものはどれですか？', 'すす', '["の", "に", "む", "すす"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '世' AND level = 8), 'reading', '「世」の読み方として正しいものはどれですか？', 'よ', '["フク", "フク", "ソウ", "よ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '整' AND level = 8), 'reading', '「整」の読み方として正しいものはどれですか？', 'ととの', '["も", "さら", "ととの", "ブ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '昔' AND level = 8), 'reading', '「昔」の読み方として正しいものはどれですか？', 'むかし', '["おも", "あい", "こおり", "むかし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '全' AND level = 8), 'reading', '「全」の読み方として正しいものはどれですか？', 'まった', '["は", "まった", "シ", "おもて"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '相' AND level = 8), 'reading', '「相」の読み方として正しいものはどれですか？', 'あい', '["さ", "まつ", "あい", "きし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '送' AND level = 8), 'reading', '「送」の読み方として正しいものはどれですか？', 'おく', '["うつ", "おく", "ひつじ", "きし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '想' AND level = 8), 'reading', '「想」の読み方として正しいものはどれですか？', 'ソウ', '["つか", "ヨ", "やまい", "ソウ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '息' AND level = 8), 'reading', '「息」の読み方として正しいものはどれですか？', 'いき', '["くすり", "たび", "いき", "はこ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '速' AND level = 8), 'reading', '「速」の読み方として正しいものはどれですか？', 'はや', '["ふで", "グ", "ひろ", "はや"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '族' AND level = 8), 'reading', '「族」の読み方として正しいものはどれですか？', 'ゾク', '["ゾク", "まった", "ち", "お"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '他' AND level = 8), 'reading', '「他」の読み方として正しいものはどれですか？', 'ほか', '["あつ", "はな", "ほか", "オウ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '打' AND level = 8), 'reading', '「打」の読み方として正しいものはどれですか？', 'う', '["う", "の", "くら", "ふえ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '対' AND level = 8), 'reading', '「対」の読み方として正しいものはどれですか？', 'タイ', '["タイ", "あい", "わる", "さま"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '待' AND level = 8), 'reading', '「待」の読み方として正しいものはどれですか？', 'ま', '["ま", "ひと", "おく", "こおり"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '代' AND level = 8), 'reading', '「代」の読み方として正しいものはどれですか？', 'か', '["か", "いき", "イン", "よこ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '第' AND level = 8), 'reading', '「第」の読み方として正しいものはどれですか？', 'ダイ', '["おく", "ダイ", "リョウ", "むかし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '題' AND level = 8), 'reading', '「題」の読み方として正しいものはどれですか？', 'ダイ', '["おも", "ダイ", "まった", "は"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '炭' AND level = 8), 'reading', '「炭」の読み方として正しいものはどれですか？', 'すみ', '["すみ", "きみ", "キュウ", "む"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '短' AND level = 8), 'reading', '「短」の読み方として正しいものはどれですか？', 'みじか', '["しな", "くすり", "リョウ", "みじか"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '談' AND level = 8), 'reading', '「談」の読み方として正しいものはどれですか？', 'ダン', '["ダン", "こおり", "にわ", "ふえ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '着' AND level = 8), 'reading', '「着」の読み方として正しいものはどれですか？', 'き', '["レツ", "き", "わる", "ふか"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '注' AND level = 8), 'reading', '「注」の読み方として正しいものはどれですか？', 'そそ', '["そそ", "や", "やまい", "ひら"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '柱' AND level = 8), 'reading', '「柱」の読み方として正しいものはどれですか？', 'はしら', '["はしら", "きみ", "ところ", "ま"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '丁' AND level = 8), 'reading', '「丁」の読み方として正しいものはどれですか？', 'チョウ', '["イ", "カン", "ヤク", "チョウ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '帳' AND level = 8), 'reading', '「帳」の読み方として正しいものはどれですか？', 'チョウ', '["チョウ", "もう", "こおり", "ひと"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '調' AND level = 8), 'reading', '「調」の読み方として正しいものはどれですか？', 'しら', '["まつ", "ひつじ", "と", "しら"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '追' AND level = 8), 'reading', '「追」の読み方として正しいものはどれですか？', 'お', '["ソウ", "やわ", "お", "よ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '定' AND level = 8), 'reading', '「定」の読み方として正しいものはどれですか？', 'さだ', '["みじか", "さだ", "いた", "たま"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '庭' AND level = 8), 'reading', '「庭」の読み方として正しいものはどれですか？', 'にわ', '["は", "にわ", "と", "はな"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '笛' AND level = 8), 'reading', '「笛」の読み方として正しいものはどれですか？', 'ふえ', '["イ", "ふえ", "みじか", "ね"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '鉄' AND level = 8), 'reading', '「鉄」の読み方として正しいものはどれですか？', 'テツ', '["テツ", "しな", "そ", "う"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '転' AND level = 8), 'reading', '「転」の読み方として正しいものはどれですか？', 'ころ', '["ころ", "ひろ", "くる", "かわ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '都' AND level = 8), 'reading', '「都」の読み方として正しいものはどれですか？', 'みやこ', '["みやこ", "おも", "レイ", "しあわ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '度' AND level = 8), 'reading', '「度」の読み方として正しいものはどれですか？', 'たび', '["たび", "ぬし", "ゆび", "や"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '投' AND level = 8), 'reading', '「投」の読み方として正しいものはどれですか？', 'な', '["しま", "な", "イ", "カイ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '豆' AND level = 8), 'reading', '「豆」の読み方として正しいものはどれですか？', 'まめ', '["ヨ", "おも", "ところ", "まめ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '島' AND level = 8), 'reading', '「島」の読み方として正しいものはどれですか？', 'しま', '["きみ", "も", "つか", "しま"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '湯' AND level = 8), 'reading', '「湯」の読み方として正しいものはどれですか？', 'ゆ', '["さら", "ベン", "ゆ", "ひと"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '登' AND level = 8), 'reading', '「登」の読み方として正しいものはどれですか？', 'のぼ', '["わる", "と", "ま", "のぼ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '等' AND level = 8), 'reading', '「等」の読み方として正しいものはどれですか？', 'ひと', '["ひと", "ダン", "わらべ", "ま"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '動' AND level = 8), 'reading', '「動」の読み方として正しいものはどれですか？', 'うご', '["ビョウ", "ショウ", "うご", "キュウ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '童' AND level = 8), 'reading', '「童」の読み方として正しいものはどれですか？', 'わらべ', '["わらべ", "す", "もの", "イ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '農' AND level = 8), 'reading', '「農」の読み方として正しいものはどれですか？', 'ノウ', '["ば", "たび", "ノウ", "ひつじ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '波' AND level = 8), 'reading', '「波」の読み方として正しいものはどれですか？', 'なみ', '["そだ", "あい", "なみ", "おも"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '配' AND level = 8), 'reading', '「配」の読み方として正しいものはどれですか？', 'くば', '["はな", "くば", "ゆだ", "そそ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '倍' AND level = 8), 'reading', '「倍」の読み方として正しいものはどれですか？', 'バイ', '["ショウ", "バイ", "なら", "コ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '箱' AND level = 8), 'reading', '「箱」の読み方として正しいものはどれですか？', 'はこ', '["はこ", "いた", "な", "ゆび"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '畑' AND level = 8), 'reading', '「畑」の読み方として正しいものはどれですか？', 'はたけ', '["ふか", "み", "はたけ", "かかり"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '発' AND level = 8), 'reading', '「発」の読み方として正しいものはどれですか？', 'ハツ', '["ハツ", "イン", "チョウ", "やす"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '反' AND level = 8), 'reading', '「反」の読み方として正しいものはどれですか？', 'そ', '["ハツ", "そ", "フク", "カイ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '坂' AND level = 8), 'reading', '「坂」の読み方として正しいものはどれですか？', 'さか', '["たい", "さか", "かな", "しら"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '板' AND level = 8), 'reading', '「板」の読み方として正しいものはどれですか？', 'いた', '["そそ", "なが", "まも", "いた"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '皮' AND level = 8), 'reading', '「皮」の読み方として正しいものはどれですか？', 'かわ', '["ば", "かわ", "みずうみ", "しな"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '悲' AND level = 8), 'reading', '「悲」の読み方として正しいものはどれですか？', 'かな', '["あ", "かな", "くば", "しら"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '美' AND level = 8), 'reading', '「美」の読み方として正しいものはどれですか？', 'うつく', '["くら", "みずうみ", "うつく", "やわ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '鼻' AND level = 8), 'reading', '「鼻」の読み方として正しいものはどれですか？', 'はな', '["うご", "はな", "すみ", "くば"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '筆' AND level = 8), 'reading', '「筆」の読み方として正しいものはどれですか？', 'ふで', '["カン", "ふで", "そ", "グ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '氷' AND level = 8), 'reading', '「氷」の読み方として正しいものはどれですか？', 'こおり', '["うつく", "こおり", "やす", "のぼ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '表' AND level = 8), 'reading', '「表」の読み方として正しいものはどれですか？', 'おもて', '["キュウ", "ま", "おもて", "あじ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '秒' AND level = 8), 'reading', '「秒」の読み方として正しいものはどれですか？', 'ビョウ', '["ビョウ", "ひつじ", "みじか", "リョウ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '病' AND level = 8), 'reading', '「病」の読み方として正しいものはどれですか？', 'やまい', '["み", "と", "やまい", "かわ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '品' AND level = 8), 'reading', '「品」の読み方として正しいものはどれですか？', 'しな', '["かな", "しな", "か", "シキ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '負' AND level = 8), 'reading', '「負」の読み方として正しいものはどれですか？', 'ま', '["ま", "みやこ", "たす", "あ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '部' AND level = 8), 'reading', '「部」の読み方として正しいものはどれですか？', 'ブ', '["ブ", "やかた", "ビョウ", "お"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '服' AND level = 8), 'reading', '「服」の読み方として正しいものはどれですか？', 'フク', '["ダイ", "フク", "ふえ", "あ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '福' AND level = 8), 'reading', '「福」の読み方として正しいものはどれですか？', 'フク', '["も", "フク", "ば", "の"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '物' AND level = 8), 'reading', '「物」の読み方として正しいものはどれですか？', 'もの', '["や", "おも", "あい", "もの"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '平' AND level = 8), 'reading', '「平」の読み方として正しいものはどれですか？', 'たい', '["たい", "あつ", "およ", "お"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '返' AND level = 8), 'reading', '「返」の読み方として正しいものはどれですか？', 'かえ', '["ころ", "しな", "あじ", "かえ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '勉' AND level = 8), 'reading', '「勉」の読み方として正しいものはどれですか？', 'ベン', '["ク", "かな", "と", "ベン"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '放' AND level = 8), 'reading', '「放」の読み方として正しいものはどれですか？', 'はな', '["はな", "さだ", "も", "よこ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '味' AND level = 8), 'reading', '「味」の読み方として正しいものはどれですか？', 'あじ', '["いき", "あじ", "きみ", "お"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '命' AND level = 8), 'reading', '「命」の読み方として正しいものはどれですか？', 'いのち', '["キ", "いのち", "そだ", "の"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '面' AND level = 8), 'reading', '「面」の読み方として正しいものはどれですか？', 'おも', '["ふか", "み", "バイ", "おも"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '問' AND level = 8), 'reading', '「問」の読み方として正しいものはどれですか？', 'と', '["まった", "カイ", "と", "くる"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '役' AND level = 8), 'reading', '「役」の読み方として正しいものはどれですか？', 'ヤク', '["ヤク", "ヨウ", "お", "うつく"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '薬' AND level = 8), 'reading', '「薬」の読み方として正しいものはどれですか？', 'くすり', '["およ", "のぼ", "すす", "くすり"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '由' AND level = 8), 'reading', '「由」の読み方として正しいものはどれですか？', 'よし', '["ふか", "よし", "のぼ", "むかし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '油' AND level = 8), 'reading', '「油」の読み方として正しいものはどれですか？', 'あぶら', '["かえ", "あぶら", "しら", "いそ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '有' AND level = 8), 'reading', '「有」の読み方として正しいものはどれですか？', 'あ', '["チョウ", "あ", "ダイ", "に"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '遊' AND level = 8), 'reading', '「遊」の読み方として正しいものはどれですか？', 'あそ', '["か", "いのち", "バイ", "あそ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '予' AND level = 8), 'reading', '「予」の読み方として正しいものはどれですか？', 'ヨ', '["リョウ", "よこ", "ふで", "ヨ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '羊' AND level = 8), 'reading', '「羊」の読み方として正しいものはどれですか？', 'ひつじ', '["ふえ", "おも", "ひつじ", "なみ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '洋' AND level = 8), 'reading', '「洋」の読み方として正しいものはどれですか？', 'ヨウ', '["ヨウ", "おもて", "すみ", "みじか"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '葉' AND level = 8), 'reading', '「葉」の読み方として正しいものはどれですか？', 'は', '["さら", "ゾク", "は", "レイ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '陽' AND level = 8), 'reading', '「陽」の読み方として正しいものはどれですか？', 'ヨウ', '["いそ", "かわ", "キ", "ヨウ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '様' AND level = 8), 'reading', '「様」の読み方として正しいものはどれですか？', 'さま', '["あそ", "みやこ", "さま", "わざ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '落' AND level = 8), 'reading', '「落」の読み方として正しいものはどれですか？', 'お', '["はな", "お", "しら", "たび"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '流' AND level = 8), 'reading', '「流」の読み方として正しいものはどれですか？', 'なが', '["う", "しな", "なが", "さけ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '旅' AND level = 8), 'reading', '「旅」の読み方として正しいものはどれですか？', 'たび', '["くすり", "はたけ", "す", "たび"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '両' AND level = 8), 'reading', '「両」の読み方として正しいものはどれですか？', 'リョウ', '["わらべ", "あたた", "リョウ", "カイ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '緑' AND level = 8), 'reading', '「緑」の読み方として正しいものはどれですか？', 'みどり', '["くる", "みどり", "タイ", "はじ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '礼' AND level = 8), 'reading', '「礼」の読み方として正しいものはどれですか？', 'レイ', '["も", "こおり", "さけ", "レイ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '列' AND level = 8), 'reading', '「列」の読み方として正しいものはどれですか？', 'レツ', '["か", "なが", "レツ", "さむ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '練' AND level = 8), 'reading', '「練」の読み方として正しいものはどれですか？', 'ね', '["さだ", "のぼ", "ね", "たい"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '路' AND level = 8), 'reading', '「路」の読み方として正しいものはどれですか？', 'じ', '["き", "じ", "キュウ", "う"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '和' AND level = 8), 'reading', '「和」の読み方として正しいものはどれですか？', 'やわ', '["やわ", "もの", "ふか", "ま"]');
