UPDATE questions SET accepted_answers = '["ひと", "いち"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '一' AND level = 10);
UPDATE questions SET accepted_answers = '["みぎ", "う", "ゆう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '右' AND level = 10);
UPDATE questions SET accepted_answers = '["あめ", "あま", "う"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '雨' AND level = 10);
UPDATE questions SET accepted_answers = '["まる", "えん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '円' AND level = 10);
UPDATE questions SET accepted_answers = '["おう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '王' AND level = 10);
UPDATE questions SET accepted_answers = '["おと", "ね", "おん", "いん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '音' AND level = 10);
UPDATE questions SET accepted_answers = '["した", "しも", "くだ", "さ", "か", "げ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '下' AND level = 10);
UPDATE questions SET accepted_answers = '["ひ", "か"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '火' AND level = 10);
UPDATE questions SET accepted_answers = '["はな", "か"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '花' AND level = 10);
UPDATE questions SET accepted_answers = '["かい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '貝' AND level = 10);
UPDATE questions SET accepted_answers = '["まな", "がく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '学' AND level = 10);
UPDATE questions SET accepted_answers = '["き", "け"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '気' AND level = 10);
UPDATE questions SET accepted_answers = '["ここの", "きゅう", "く"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '九' AND level = 10);
UPDATE questions SET accepted_answers = '["やす", "きゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '休' AND level = 10);
UPDATE questions SET accepted_answers = '["たま", "ぎょく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '玉' AND level = 10);
UPDATE questions SET accepted_answers = '["かね", "きん", "こん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '金' AND level = 10);
UPDATE questions SET accepted_answers = '["そら", "あ", "から", "くう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '空' AND level = 10);
UPDATE questions SET accepted_answers = '["つき", "げつ", "がつ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '月' AND level = 10);
UPDATE questions SET accepted_answers = '["いぬ", "けん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '犬' AND level = 10);
UPDATE questions SET accepted_answers = '["み", "けん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '見' AND level = 10);
UPDATE questions SET accepted_answers = '["いつ", "ご"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '五' AND level = 10);
UPDATE questions SET accepted_answers = '["くち", "こう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '口' AND level = 10);
UPDATE questions SET accepted_answers = '["こう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '校' AND level = 10);
UPDATE questions SET accepted_answers = '["ひだり", "さ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '左' AND level = 10);
UPDATE questions SET accepted_answers = '["み", "さん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '三' AND level = 10);
UPDATE questions SET accepted_answers = '["やま", "さん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '山' AND level = 10);
UPDATE questions SET accepted_answers = '["こ", "し", "す"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '子' AND level = 10);
UPDATE questions SET accepted_answers = '["よ", "し"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '四' AND level = 10);
UPDATE questions SET accepted_answers = '["いと", "し"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '糸' AND level = 10);
UPDATE questions SET accepted_answers = '["じ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '字' AND level = 10);
UPDATE questions SET accepted_answers = '["みみ", "じ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '耳' AND level = 10);
UPDATE questions SET accepted_answers = '["なな", "しち"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '七' AND level = 10);
UPDATE questions SET accepted_answers = '["くるま", "しゃ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '車' AND level = 10);
UPDATE questions SET accepted_answers = '["て", "しゅ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '手' AND level = 10);
UPDATE questions SET accepted_answers = '["とお", "と", "じゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '十' AND level = 10);
UPDATE questions SET accepted_answers = '["で", "だ", "しゅつ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '出' AND level = 10);
UPDATE questions SET accepted_answers = '["おんな", "じょ", "にょ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '女' AND level = 10);
UPDATE questions SET accepted_answers = '["ちい", "しょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '小' AND level = 10);
UPDATE questions SET accepted_answers = '["うえ", "あ", "のぼ", "じょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '上' AND level = 10);
UPDATE questions SET accepted_answers = '["もり", "しん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '森' AND level = 10);
UPDATE questions SET accepted_answers = '["ひと", "じん", "にん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '人' AND level = 10);
UPDATE questions SET accepted_answers = '["みず", "すい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '水' AND level = 10);
UPDATE questions SET accepted_answers = '["ただ", "せい", "しょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '正' AND level = 10);
UPDATE questions SET accepted_answers = '["い", "う", "なま", "せい", "しょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '生' AND level = 10);
UPDATE questions SET accepted_answers = '["あお", "せい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '青' AND level = 10);
UPDATE questions SET accepted_answers = '["ゆう", "せき"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '夕' AND level = 10);
UPDATE questions SET accepted_answers = '["いし", "せき", "しゃく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '石' AND level = 10);
UPDATE questions SET accepted_answers = '["あか", "せき"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '赤' AND level = 10);
UPDATE questions SET accepted_answers = '["ち", "せん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '千' AND level = 10);
UPDATE questions SET accepted_answers = '["かわ", "せん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '川' AND level = 10);
UPDATE questions SET accepted_answers = '["さき", "せん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '先' AND level = 10);
UPDATE questions SET accepted_answers = '["はや", "そう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '早' AND level = 10);
UPDATE questions SET accepted_answers = '["くさ", "そう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '草' AND level = 10);
UPDATE questions SET accepted_answers = '["あし", "た", "そく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '足' AND level = 10);
UPDATE questions SET accepted_answers = '["むら", "そん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '村' AND level = 10);
UPDATE questions SET accepted_answers = '["おお", "だい", "たい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '大' AND level = 10);
UPDATE questions SET accepted_answers = '["おとこ", "だん", "なん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '男' AND level = 10);
UPDATE questions SET accepted_answers = '["たけ", "ちく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '竹' AND level = 10);
UPDATE questions SET accepted_answers = '["なか", "ちゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '中' AND level = 10);
UPDATE questions SET accepted_answers = '["むし", "ちゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '虫' AND level = 10);
UPDATE questions SET accepted_answers = '["まち", "ちょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '町' AND level = 10);
UPDATE questions SET accepted_answers = '["てん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '天' AND level = 10);
UPDATE questions SET accepted_answers = '["た", "でん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '田' AND level = 10);
UPDATE questions SET accepted_answers = '["つち", "ど", "と"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '土' AND level = 10);
UPDATE questions SET accepted_answers = '["ふた", "に"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '二' AND level = 10);
UPDATE questions SET accepted_answers = '["ひ", "か", "にち", "じつ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '日' AND level = 10);
UPDATE questions SET accepted_answers = '["い", "はい", "にゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '入' AND level = 10);
UPDATE questions SET accepted_answers = '["とし", "ねん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '年' AND level = 10);
UPDATE questions SET accepted_answers = '["しろ", "はく", "びゃく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '白' AND level = 10);
UPDATE questions SET accepted_answers = '["や", "はち"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '八' AND level = 10);
UPDATE questions SET accepted_answers = '["ひゃく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '百' AND level = 10);
UPDATE questions SET accepted_answers = '["ふみ", "ぶん", "もん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '文' AND level = 10);
UPDATE questions SET accepted_answers = '["き", "もく", "ぼく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '木' AND level = 10);
UPDATE questions SET accepted_answers = '["もと", "ほん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '本' AND level = 10);
UPDATE questions SET accepted_answers = '["な", "めい", "みょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '名' AND level = 10);
UPDATE questions SET accepted_answers = '["め", "もく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '目' AND level = 10);
UPDATE questions SET accepted_answers = '["た", "りつ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '立' AND level = 10);
UPDATE questions SET accepted_answers = '["ちから", "りょく", "りき"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '力' AND level = 10);
UPDATE questions SET accepted_answers = '["はやし", "りん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '林' AND level = 10);
UPDATE questions SET accepted_answers = '["む", "ろく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '六' AND level = 10);
UPDATE questions SET accepted_answers = '["ひ", "いん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '引' AND level = 9);
UPDATE questions SET accepted_answers = '["は", "はね", "う"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '羽' AND level = 9);
UPDATE questions SET accepted_answers = '["くも", "うん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '雲' AND level = 9);
UPDATE questions SET accepted_answers = '["その", "えん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '園' AND level = 9);
UPDATE questions SET accepted_answers = '["とお", "えん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '遠' AND level = 9);
UPDATE questions SET accepted_answers = '["なに", "なん", "か"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '何' AND level = 9);
UPDATE questions SET accepted_answers = '["か"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '科' AND level = 9);
UPDATE questions SET accepted_answers = '["なつ", "か"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '夏' AND level = 9);
UPDATE questions SET accepted_answers = '["いえ", "や", "か", "け"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '家' AND level = 9);
UPDATE questions SET accepted_answers = '["うた", "か"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '歌' AND level = 9);
UPDATE questions SET accepted_answers = '["が", "かく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '画' AND level = 9);
UPDATE questions SET accepted_answers = '["まわ", "かい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '回' AND level = 9);
UPDATE questions SET accepted_answers = '["あ", "かい", "え"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '会' AND level = 9);
UPDATE questions SET accepted_answers = '["うみ", "かい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '海' AND level = 9);
UPDATE questions SET accepted_answers = '["かい", "え"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '絵' AND level = 9);
UPDATE questions SET accepted_answers = '["そと", "がい", "げ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '外' AND level = 9);
UPDATE questions SET accepted_answers = '["かど", "つの", "かく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '角' AND level = 9);
UPDATE questions SET accepted_answers = '["たの", "がく", "らく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '楽' AND level = 9);
UPDATE questions SET accepted_answers = '["かつ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '活' AND level = 9);
UPDATE questions SET accepted_answers = '["あいだ", "ま", "かん", "けん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '間' AND level = 9);
UPDATE questions SET accepted_answers = '["まる", "がん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '丸' AND level = 9);
UPDATE questions SET accepted_answers = '["いわ", "がん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '岩' AND level = 9);
UPDATE questions SET accepted_answers = '["かお", "がん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '顔' AND level = 9);
UPDATE questions SET accepted_answers = '["き"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '汽' AND level = 9);
UPDATE questions SET accepted_answers = '["しる", "き"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '記' AND level = 9);
UPDATE questions SET accepted_answers = '["かえ", "き"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '帰' AND level = 9);
UPDATE questions SET accepted_answers = '["ゆみ", "きゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '弓' AND level = 9);
UPDATE questions SET accepted_answers = '["うし", "ぎゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '牛' AND level = 9);
UPDATE questions SET accepted_answers = '["うお", "さかな", "ぎょ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '魚' AND level = 9);
UPDATE questions SET accepted_answers = '["きょう", "けい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '京' AND level = 9);
UPDATE questions SET accepted_answers = '["つよ", "きょう", "ごう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '強' AND level = 9);
UPDATE questions SET accepted_answers = '["おし", "きょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '教' AND level = 9);
UPDATE questions SET accepted_answers = '["ちか", "きん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '近' AND level = 9);
UPDATE questions SET accepted_answers = '["あに", "けい", "きょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '兄' AND level = 9);
UPDATE questions SET accepted_answers = '["かたち", "けい", "ぎょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '形' AND level = 9);
UPDATE questions SET accepted_answers = '["はか", "けい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '計' AND level = 9);
UPDATE questions SET accepted_answers = '["もと", "げん", "がん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '元' AND level = 9);
UPDATE questions SET accepted_answers = '["い", "げん", "ごん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '言' AND level = 9);
UPDATE questions SET accepted_answers = '["はら", "げん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '原' AND level = 9);
UPDATE questions SET accepted_answers = '["と", "こ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '戸' AND level = 9);
UPDATE questions SET accepted_answers = '["ふる", "こ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '古' AND level = 9);
UPDATE questions SET accepted_answers = '["ご"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '午' AND level = 9);
UPDATE questions SET accepted_answers = '["のち", "うし", "ご", "こう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '後' AND level = 9);
UPDATE questions SET accepted_answers = '["かた", "ご"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '語' AND level = 9);
UPDATE questions SET accepted_answers = '["こう", "く"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '工' AND level = 9);
UPDATE questions SET accepted_answers = '["おおやけ", "こう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '公' AND level = 9);
UPDATE questions SET accepted_answers = '["ひろ", "こう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '広' AND level = 9);
UPDATE questions SET accepted_answers = '["まじ", "こう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '交' AND level = 9);
UPDATE questions SET accepted_answers = '["ひかり", "こう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '光' AND level = 9);
UPDATE questions SET accepted_answers = '["かんが", "こう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '考' AND level = 9);
UPDATE questions SET accepted_answers = '["い", "こう", "ぎょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '行' AND level = 9);
UPDATE questions SET accepted_answers = '["たか", "こう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '高' AND level = 9);
UPDATE questions SET accepted_answers = '["き", "こう", "おう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '黄' AND level = 9);
UPDATE questions SET accepted_answers = '["あ", "ごう", "がっ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '合' AND level = 9);
UPDATE questions SET accepted_answers = '["たに", "こく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '谷' AND level = 9);
UPDATE questions SET accepted_answers = '["くに", "こく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '国' AND level = 9);
UPDATE questions SET accepted_answers = '["くろ", "こく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '黒' AND level = 9);
UPDATE questions SET accepted_answers = '["いま", "こん", "きん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '今' AND level = 9);
UPDATE questions SET accepted_answers = '["さい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '才' AND level = 9);
UPDATE questions SET accepted_answers = '["ほそ", "さい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '細' AND level = 9);
UPDATE questions SET accepted_answers = '["つく", "さく", "さ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '作' AND level = 9);
UPDATE questions SET accepted_answers = '["さん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '算' AND level = 9);
UPDATE questions SET accepted_answers = '["と", "し"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '止' AND level = 9);
UPDATE questions SET accepted_answers = '["いち", "し"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '市' AND level = 9);
UPDATE questions SET accepted_answers = '["や", "し"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '矢' AND level = 9);
UPDATE questions SET accepted_answers = '["あね", "し"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '姉' AND level = 9);
UPDATE questions SET accepted_answers = '["おも", "し"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '思' AND level = 9);
UPDATE questions SET accepted_answers = '["かみ", "し"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '紙' AND level = 9);
UPDATE questions SET accepted_answers = '["てら", "じ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '寺' AND level = 9);
UPDATE questions SET accepted_answers = '["みずか", "じ", "し"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '自' AND level = 9);
UPDATE questions SET accepted_answers = '["とき", "じ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '時' AND level = 9);
UPDATE questions SET accepted_answers = '["むろ", "しつ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '室' AND level = 9);
UPDATE questions SET accepted_answers = '["やしろ", "しゃ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '社' AND level = 9);
UPDATE questions SET accepted_answers = '["よわ", "じゃく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '弱' AND level = 9);
UPDATE questions SET accepted_answers = '["くび", "しゅ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '首' AND level = 9);
UPDATE questions SET accepted_answers = '["あき", "しゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '秋' AND level = 9);
UPDATE questions SET accepted_answers = '["しゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '週' AND level = 9);
UPDATE questions SET accepted_answers = '["はる", "しゅん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '春' AND level = 9);
UPDATE questions SET accepted_answers = '["か", "しょ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '書' AND level = 9);
UPDATE questions SET accepted_answers = '["すく", "しょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '少' AND level = 9);
UPDATE questions SET accepted_answers = '["ば", "じょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '場' AND level = 9);
UPDATE questions SET accepted_answers = '["いろ", "しょく", "しき"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '色' AND level = 9);
UPDATE questions SET accepted_answers = '["た", "しょく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '食' AND level = 9);
UPDATE questions SET accepted_answers = '["こころ", "しん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '心' AND level = 9);
UPDATE questions SET accepted_answers = '["あたら", "しん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '新' AND level = 9);
UPDATE questions SET accepted_answers = '["おや", "しん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '親' AND level = 9);
UPDATE questions SET accepted_answers = '["はか", "ず", "と"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '図' AND level = 9);
UPDATE questions SET accepted_answers = '["かず", "すう", "す"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '数' AND level = 9);
UPDATE questions SET accepted_answers = '["にし", "せい", "さい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '西' AND level = 9);
UPDATE questions SET accepted_answers = '["こえ", "せい", "しょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '声' AND level = 9);
UPDATE questions SET accepted_answers = '["ほし", "せい", "しょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '星' AND level = 9);
UPDATE questions SET accepted_answers = '["は", "せい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '晴' AND level = 9);
UPDATE questions SET accepted_answers = '["き", "せつ", "さい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '切' AND level = 9);
UPDATE questions SET accepted_answers = '["ゆき", "せつ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '雪' AND level = 9);
UPDATE questions SET accepted_answers = '["ふね", "せん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '船' AND level = 9);
UPDATE questions SET accepted_answers = '["せん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '線' AND level = 9);
UPDATE questions SET accepted_answers = '["まえ", "ぜん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '前' AND level = 9);
UPDATE questions SET accepted_answers = '["く", "そ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '組' AND level = 9);
UPDATE questions SET accepted_answers = '["はし", "そう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '走' AND level = 9);
UPDATE questions SET accepted_answers = '["おお", "た"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '多' AND level = 9);
UPDATE questions SET accepted_answers = '["ふと", "たい", "た"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '太' AND level = 9);
UPDATE questions SET accepted_answers = '["からだ", "たい", "てい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '体' AND level = 9);
UPDATE questions SET accepted_answers = '["だい", "たい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '台' AND level = 9);
UPDATE questions SET accepted_answers = '["ち", "じ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '地' AND level = 9);
UPDATE questions SET accepted_answers = '["いけ", "ち"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '池' AND level = 9);
UPDATE questions SET accepted_answers = '["し", "ち"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '知' AND level = 9);
UPDATE questions SET accepted_answers = '["ちゃ", "さ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '茶' AND level = 9);
UPDATE questions SET accepted_answers = '["ひる", "ちゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '昼' AND level = 9);
UPDATE questions SET accepted_answers = '["なが", "ちょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '長' AND level = 9);
UPDATE questions SET accepted_answers = '["とり", "ちょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '鳥' AND level = 9);
UPDATE questions SET accepted_answers = '["あさ", "ちょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '朝' AND level = 9);
UPDATE questions SET accepted_answers = '["なお", "ちょく", "じき"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '直' AND level = 9);
UPDATE questions SET accepted_answers = '["とお", "つう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '通' AND level = 9);
UPDATE questions SET accepted_answers = '["おとうと", "てい", "だい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '弟' AND level = 9);
UPDATE questions SET accepted_answers = '["みせ", "てん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '店' AND level = 9);
UPDATE questions SET accepted_answers = '["てん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '点' AND level = 9);
UPDATE questions SET accepted_answers = '["でん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '電' AND level = 9);
UPDATE questions SET accepted_answers = '["かたな", "とう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '刀' AND level = 9);
UPDATE questions SET accepted_answers = '["ふゆ", "とう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '冬' AND level = 9);
UPDATE questions SET accepted_answers = '["あ", "とう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '当' AND level = 9);
UPDATE questions SET accepted_answers = '["ひがし", "とう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '東' AND level = 9);
UPDATE questions SET accepted_answers = '["こた", "とう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '答' AND level = 9);
UPDATE questions SET accepted_answers = '["あたま", "とう", "ず"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '頭' AND level = 9);
UPDATE questions SET accepted_answers = '["おな", "どう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '同' AND level = 9);
UPDATE questions SET accepted_answers = '["みち", "どう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '道' AND level = 9);
UPDATE questions SET accepted_answers = '["よ", "どく", "とう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '読' AND level = 9);
UPDATE questions SET accepted_answers = '["うち", "ない", "だい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '内' AND level = 9);
UPDATE questions SET accepted_answers = '["みなみ", "なん", "な"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '南' AND level = 9);
UPDATE questions SET accepted_answers = '["にく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '肉' AND level = 9);
UPDATE questions SET accepted_answers = '["うま", "ば"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '馬' AND level = 9);
UPDATE questions SET accepted_answers = '["う", "ばい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '売' AND level = 9);
UPDATE questions SET accepted_answers = '["か", "ばい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '買' AND level = 9);
UPDATE questions SET accepted_answers = '["むぎ", "ばく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '麦' AND level = 9);
UPDATE questions SET accepted_answers = '["なか", "はん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '半' AND level = 9);
UPDATE questions SET accepted_answers = '["ばん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '番' AND level = 9);
UPDATE questions SET accepted_answers = '["ちち", "ふ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '父' AND level = 9);
UPDATE questions SET accepted_answers = '["かぜ", "ふう", "ふ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '風' AND level = 9);
UPDATE questions SET accepted_answers = '["わ", "ぶん", "ふん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '分' AND level = 9);
UPDATE questions SET accepted_answers = '["き", "ぶん", "もん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '聞' AND level = 9);
UPDATE questions SET accepted_answers = '["こめ", "べい", "まい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '米' AND level = 9);
UPDATE questions SET accepted_answers = '["ある", "ほ", "ぶ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '歩' AND level = 9);
UPDATE questions SET accepted_answers = '["はは", "ぼ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '母' AND level = 9);
UPDATE questions SET accepted_answers = '["かた", "ほう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '方' AND level = 9);
UPDATE questions SET accepted_answers = '["きた", "ほく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '北' AND level = 9);
UPDATE questions SET accepted_answers = '["まい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '毎' AND level = 9);
UPDATE questions SET accepted_answers = '["いもうと", "まい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '妹' AND level = 9);
UPDATE questions SET accepted_answers = '["まん", "ばん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '万' AND level = 9);
UPDATE questions SET accepted_answers = '["あか", "めい", "みょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '明' AND level = 9);
UPDATE questions SET accepted_answers = '["な", "めい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '鳴' AND level = 9);
UPDATE questions SET accepted_answers = '["け", "もう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '毛' AND level = 9);
UPDATE questions SET accepted_answers = '["かど", "もん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '門' AND level = 9);
UPDATE questions SET accepted_answers = '["よ", "よる", "や"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '夜' AND level = 9);
UPDATE questions SET accepted_answers = '["の", "や"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '野' AND level = 9);
UPDATE questions SET accepted_answers = '["とも", "ゆう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '友' AND level = 9);
UPDATE questions SET accepted_answers = '["もち", "よう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '用' AND level = 9);
UPDATE questions SET accepted_answers = '["よう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '曜' AND level = 9);
UPDATE questions SET accepted_answers = '["く", "らい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '来' AND level = 9);
UPDATE questions SET accepted_answers = '["さと", "り"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '里' AND level = 9);
UPDATE questions SET accepted_answers = '["り"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '理' AND level = 9);
UPDATE questions SET accepted_answers = '["はな", "わ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '話' AND level = 9);
UPDATE questions SET accepted_answers = '["わる", "あく", "お"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '悪' AND level = 8);
UPDATE questions SET accepted_answers = '["やす", "あん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '安' AND level = 8);
UPDATE questions SET accepted_answers = '["くら", "あん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '暗' AND level = 8);
UPDATE questions SET accepted_answers = '["い"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '医' AND level = 8);
UPDATE questions SET accepted_answers = '["ゆだ", "い"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '委' AND level = 8);
UPDATE questions SET accepted_answers = '["い"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '意' AND level = 8);
UPDATE questions SET accepted_answers = '["そだ", "いく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '育' AND level = 8);
UPDATE questions SET accepted_answers = '["いん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '員' AND level = 8);
UPDATE questions SET accepted_answers = '["いん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '院' AND level = 8);
UPDATE questions SET accepted_answers = '["の", "いん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '飲' AND level = 8);
UPDATE questions SET accepted_answers = '["はこ", "うん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '運' AND level = 8);
UPDATE questions SET accepted_answers = '["およ", "えい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '泳' AND level = 8);
UPDATE questions SET accepted_answers = '["えき"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '駅' AND level = 8);
UPDATE questions SET accepted_answers = '["おう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '央' AND level = 8);
UPDATE questions SET accepted_answers = '["よこ", "おう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '横' AND level = 8);
UPDATE questions SET accepted_answers = '["や", "おく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '屋' AND level = 8);
UPDATE questions SET accepted_answers = '["あたた", "おん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '温' AND level = 8);
UPDATE questions SET accepted_answers = '["ば", "か", "け"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '化' AND level = 8);
UPDATE questions SET accepted_answers = '["に", "か"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '荷' AND level = 8);
UPDATE questions SET accepted_answers = '["かい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '界' AND level = 8);
UPDATE questions SET accepted_answers = '["ひら", "あ", "かい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '開' AND level = 8);
UPDATE questions SET accepted_answers = '["かい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '階' AND level = 8);
UPDATE questions SET accepted_answers = '["さむ", "かん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '寒' AND level = 8);
UPDATE questions SET accepted_answers = '["かん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '感' AND level = 8);
UPDATE questions SET accepted_answers = '["かん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '漢' AND level = 8);
UPDATE questions SET accepted_answers = '["やかた", "かん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '館' AND level = 8);
UPDATE questions SET accepted_answers = '["きし", "がん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '岸' AND level = 8);
UPDATE questions SET accepted_answers = '["お", "き"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '起' AND level = 8);
UPDATE questions SET accepted_answers = '["き", "ご"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '期' AND level = 8);
UPDATE questions SET accepted_answers = '["きゃく", "かく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '客' AND level = 8);
UPDATE questions SET accepted_answers = '["きわ", "きゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '究' AND level = 8);
UPDATE questions SET accepted_answers = '["いそ", "きゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '急' AND level = 8);
UPDATE questions SET accepted_answers = '["きゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '級' AND level = 8);
UPDATE questions SET accepted_answers = '["みや", "きゅう", "ぐう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '宮' AND level = 8);
UPDATE questions SET accepted_answers = '["たま", "きゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '球' AND level = 8);
UPDATE questions SET accepted_answers = '["さ", "きょ", "こ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '去' AND level = 8);
UPDATE questions SET accepted_answers = '["はし", "きょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '橋' AND level = 8);
UPDATE questions SET accepted_answers = '["わざ", "ぎょう", "ごう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '業' AND level = 8);
UPDATE questions SET accepted_answers = '["ま", "きょく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '曲' AND level = 8);
UPDATE questions SET accepted_answers = '["きょく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '局' AND level = 8);
UPDATE questions SET accepted_answers = '["ぎん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '銀' AND level = 8);
UPDATE questions SET accepted_answers = '["く"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '区' AND level = 8);
UPDATE questions SET accepted_answers = '["くる", "にが", "く"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '苦' AND level = 8);
UPDATE questions SET accepted_answers = '["ぐ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '具' AND level = 8);
UPDATE questions SET accepted_answers = '["きみ", "くん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '君' AND level = 8);
UPDATE questions SET accepted_answers = '["かかり", "かか", "けい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '係' AND level = 8);
UPDATE questions SET accepted_answers = '["かる", "けい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '軽' AND level = 8);
UPDATE questions SET accepted_answers = '["ち", "けつ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '血' AND level = 8);
UPDATE questions SET accepted_answers = '["き", "けつ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '決' AND level = 8);
UPDATE questions SET accepted_answers = '["と", "けん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '研' AND level = 8);
UPDATE questions SET accepted_answers = '["けん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '県' AND level = 8);
UPDATE questions SET accepted_answers = '["こ", "く"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '庫' AND level = 8);
UPDATE questions SET accepted_answers = '["みずうみ", "こ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '湖' AND level = 8);
UPDATE questions SET accepted_answers = '["む", "こう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '向' AND level = 8);
UPDATE questions SET accepted_answers = '["しあわ", "こう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '幸' AND level = 8);
UPDATE questions SET accepted_answers = '["みなと", "こう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '港' AND level = 8);
UPDATE questions SET accepted_answers = '["ごう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '号' AND level = 8);
UPDATE questions SET accepted_answers = '["ね", "こん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '根' AND level = 8);
UPDATE questions SET accepted_answers = '["まつ", "さい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '祭' AND level = 8);
UPDATE questions SET accepted_answers = '["さら"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '皿' AND level = 8);
UPDATE questions SET accepted_answers = '["つか", "し", "じ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '仕' AND level = 8);
UPDATE questions SET accepted_answers = '["し"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '死' AND level = 8);
UPDATE questions SET accepted_answers = '["つか", "し"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '使' AND level = 8);
UPDATE questions SET accepted_answers = '["はじ", "し"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '始' AND level = 8);
UPDATE questions SET accepted_answers = '["ゆび", "さ", "し"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '指' AND level = 8);
UPDATE questions SET accepted_answers = '["は", "し"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '歯' AND level = 8);
UPDATE questions SET accepted_answers = '["し"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '詩' AND level = 8);
UPDATE questions SET accepted_answers = '["つぎ", "つ", "じ", "し"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '次' AND level = 8);
UPDATE questions SET accepted_answers = '["こと", "じ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '事' AND level = 8);
UPDATE questions SET accepted_answers = '["も", "じ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '持' AND level = 8);
UPDATE questions SET accepted_answers = '["しき"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '式' AND level = 8);
UPDATE questions SET accepted_answers = '["み", "みの", "じつ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '実' AND level = 8);
UPDATE questions SET accepted_answers = '["うつ", "しゃ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '写' AND level = 8);
UPDATE questions SET accepted_answers = '["もの", "しゃ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '者' AND level = 8);
UPDATE questions SET accepted_answers = '["ぬし", "おも", "しゅ", "す"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '主' AND level = 8);
UPDATE questions SET accepted_answers = '["まも", "しゅ", "す"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '守' AND level = 8);
UPDATE questions SET accepted_answers = '["と", "しゅ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '取' AND level = 8);
UPDATE questions SET accepted_answers = '["さけ", "しゅ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '酒' AND level = 8);
UPDATE questions SET accepted_answers = '["う", "じゅ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '受' AND level = 8);
UPDATE questions SET accepted_answers = '["す", "しゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '州' AND level = 8);
UPDATE questions SET accepted_answers = '["ひろ", "しゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '拾' AND level = 8);
UPDATE questions SET accepted_answers = '["お", "しゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '終' AND level = 8);
UPDATE questions SET accepted_answers = '["なら", "しゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '習' AND level = 8);
UPDATE questions SET accepted_answers = '["あつ", "しゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '集' AND level = 8);
UPDATE questions SET accepted_answers = '["す", "じゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '住' AND level = 8);
UPDATE questions SET accepted_answers = '["おも", "かさ", "じゅう", "ちょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '重' AND level = 8);
UPDATE questions SET accepted_answers = '["やど", "しゅく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '宿' AND level = 8);
UPDATE questions SET accepted_answers = '["ところ", "しょ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '所' AND level = 8);
UPDATE questions SET accepted_answers = '["あつ", "しょ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '暑' AND level = 8);
UPDATE questions SET accepted_answers = '["たす", "じょ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '助' AND level = 8);
UPDATE questions SET accepted_answers = '["しょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '昭' AND level = 8);
UPDATE questions SET accepted_answers = '["き", "しょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '消' AND level = 8);
UPDATE questions SET accepted_answers = '["あきな", "しょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '商' AND level = 8);
UPDATE questions SET accepted_answers = '["しょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '章' AND level = 8);
UPDATE questions SET accepted_answers = '["か", "しょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '勝' AND level = 8);
UPDATE questions SET accepted_answers = '["の", "じょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '乗' AND level = 8);
UPDATE questions SET accepted_answers = '["う", "しょく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '植' AND level = 8);
UPDATE questions SET accepted_answers = '["もう", "しん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '申' AND level = 8);
UPDATE questions SET accepted_answers = '["み", "しん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '身' AND level = 8);
UPDATE questions SET accepted_answers = '["かみ", "しん", "じん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '神' AND level = 8);
UPDATE questions SET accepted_answers = '["ま", "しん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '真' AND level = 8);
UPDATE questions SET accepted_answers = '["ふか", "しん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '深' AND level = 8);
UPDATE questions SET accepted_answers = '["すす", "しん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '進' AND level = 8);
UPDATE questions SET accepted_answers = '["よ", "せい", "せ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '世' AND level = 8);
UPDATE questions SET accepted_answers = '["ととの", "せい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '整' AND level = 8);
UPDATE questions SET accepted_answers = '["むかし", "せき"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '昔' AND level = 8);
UPDATE questions SET accepted_answers = '["まった", "ぜん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '全' AND level = 8);
UPDATE questions SET accepted_answers = '["あい", "そう", "しょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '相' AND level = 8);
UPDATE questions SET accepted_answers = '["おく", "そう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '送' AND level = 8);
UPDATE questions SET accepted_answers = '["そう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '想' AND level = 8);
UPDATE questions SET accepted_answers = '["いき", "そく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '息' AND level = 8);
UPDATE questions SET accepted_answers = '["はや", "そく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '速' AND level = 8);
UPDATE questions SET accepted_answers = '["ぞく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '族' AND level = 8);
UPDATE questions SET accepted_answers = '["ほか", "た"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '他' AND level = 8);
UPDATE questions SET accepted_answers = '["う", "だ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '打' AND level = 8);
UPDATE questions SET accepted_answers = '["たい", "つい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '対' AND level = 8);
UPDATE questions SET accepted_answers = '["ま", "たい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '待' AND level = 8);
UPDATE questions SET accepted_answers = '["か", "よ", "だい", "たい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '代' AND level = 8);
UPDATE questions SET accepted_answers = '["だい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '第' AND level = 8);
UPDATE questions SET accepted_answers = '["だい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '題' AND level = 8);
UPDATE questions SET accepted_answers = '["すみ", "たん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '炭' AND level = 8);
UPDATE questions SET accepted_answers = '["みじか", "たん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '短' AND level = 8);
UPDATE questions SET accepted_answers = '["だん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '談' AND level = 8);
UPDATE questions SET accepted_answers = '["き", "つ", "ちゃく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '着' AND level = 8);
UPDATE questions SET accepted_answers = '["そそ", "ちゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '注' AND level = 8);
UPDATE questions SET accepted_answers = '["はしら", "ちゅう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '柱' AND level = 8);
UPDATE questions SET accepted_answers = '["ちょう", "てい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '丁' AND level = 8);
UPDATE questions SET accepted_answers = '["ちょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '帳' AND level = 8);
UPDATE questions SET accepted_answers = '["しら", "ちょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '調' AND level = 8);
UPDATE questions SET accepted_answers = '["お", "つい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '追' AND level = 8);
UPDATE questions SET accepted_answers = '["さだ", "てい", "じょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '定' AND level = 8);
UPDATE questions SET accepted_answers = '["にわ", "てい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '庭' AND level = 8);
UPDATE questions SET accepted_answers = '["ふえ", "てき"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '笛' AND level = 8);
UPDATE questions SET accepted_answers = '["てつ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '鉄' AND level = 8);
UPDATE questions SET accepted_answers = '["ころ", "てん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '転' AND level = 8);
UPDATE questions SET accepted_answers = '["みやこ", "と", "つ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '都' AND level = 8);
UPDATE questions SET accepted_answers = '["たび", "ど", "と"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '度' AND level = 8);
UPDATE questions SET accepted_answers = '["な", "とう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '投' AND level = 8);
UPDATE questions SET accepted_answers = '["まめ", "とう", "ず"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '豆' AND level = 8);
UPDATE questions SET accepted_answers = '["しま", "とう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '島' AND level = 8);
UPDATE questions SET accepted_answers = '["ゆ", "とう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '湯' AND level = 8);
UPDATE questions SET accepted_answers = '["のぼ", "とう", "と"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '登' AND level = 8);
UPDATE questions SET accepted_answers = '["ひと", "とう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '等' AND level = 8);
UPDATE questions SET accepted_answers = '["うご", "どう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '動' AND level = 8);
UPDATE questions SET accepted_answers = '["わらべ", "どう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '童' AND level = 8);
UPDATE questions SET accepted_answers = '["のう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '農' AND level = 8);
UPDATE questions SET accepted_answers = '["なみ", "は"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '波' AND level = 8);
UPDATE questions SET accepted_answers = '["くば", "はい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '配' AND level = 8);
UPDATE questions SET accepted_answers = '["ばい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '倍' AND level = 8);
UPDATE questions SET accepted_answers = '["はこ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '箱' AND level = 8);
UPDATE questions SET accepted_answers = '["はたけ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '畑' AND level = 8);
UPDATE questions SET accepted_answers = '["はつ", "ほつ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '発' AND level = 8);
UPDATE questions SET accepted_answers = '["そ", "はん", "ほん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '反' AND level = 8);
UPDATE questions SET accepted_answers = '["さか", "はん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '坂' AND level = 8);
UPDATE questions SET accepted_answers = '["いた", "はん", "ばん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '板' AND level = 8);
UPDATE questions SET accepted_answers = '["かわ", "ひ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '皮' AND level = 8);
UPDATE questions SET accepted_answers = '["かな", "ひ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '悲' AND level = 8);
UPDATE questions SET accepted_answers = '["うつく", "び"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '美' AND level = 8);
UPDATE questions SET accepted_answers = '["はな", "び"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '鼻' AND level = 8);
UPDATE questions SET accepted_answers = '["ふで", "ひつ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '筆' AND level = 8);
UPDATE questions SET accepted_answers = '["こおり", "ひょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '氷' AND level = 8);
UPDATE questions SET accepted_answers = '["おもて", "あらわ", "ひょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '表' AND level = 8);
UPDATE questions SET accepted_answers = '["びょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '秒' AND level = 8);
UPDATE questions SET accepted_answers = '["やまい", "びょう", "へい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '病' AND level = 8);
UPDATE questions SET accepted_answers = '["しな", "ひん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '品' AND level = 8);
UPDATE questions SET accepted_answers = '["ま", "お", "ふ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '負' AND level = 8);
UPDATE questions SET accepted_answers = '["ぶ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '部' AND level = 8);
UPDATE questions SET accepted_answers = '["ふく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '服' AND level = 8);
UPDATE questions SET accepted_answers = '["ふく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '福' AND level = 8);
UPDATE questions SET accepted_answers = '["もの", "ぶつ", "もつ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '物' AND level = 8);
UPDATE questions SET accepted_answers = '["たい", "へい", "びょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '平' AND level = 8);
UPDATE questions SET accepted_answers = '["かえ", "へん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '返' AND level = 8);
UPDATE questions SET accepted_answers = '["べん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '勉' AND level = 8);
UPDATE questions SET accepted_answers = '["はな", "ほう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '放' AND level = 8);
UPDATE questions SET accepted_answers = '["あじ", "み"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '味' AND level = 8);
UPDATE questions SET accepted_answers = '["いのち", "めい", "みょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '命' AND level = 8);
UPDATE questions SET accepted_answers = '["おも", "つら", "めん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '面' AND level = 8);
UPDATE questions SET accepted_answers = '["と", "もん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '問' AND level = 8);
UPDATE questions SET accepted_answers = '["やく", "えき"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '役' AND level = 8);
UPDATE questions SET accepted_answers = '["くすり", "やく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '薬' AND level = 8);
UPDATE questions SET accepted_answers = '["よし", "ゆ", "ゆう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '由' AND level = 8);
UPDATE questions SET accepted_answers = '["あぶら", "ゆ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '油' AND level = 8);
UPDATE questions SET accepted_answers = '["あ", "ゆう", "う"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '有' AND level = 8);
UPDATE questions SET accepted_answers = '["あそ", "ゆう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '遊' AND level = 8);
UPDATE questions SET accepted_answers = '["よ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '予' AND level = 8);
UPDATE questions SET accepted_answers = '["ひつじ", "よう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '羊' AND level = 8);
UPDATE questions SET accepted_answers = '["よう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '洋' AND level = 8);
UPDATE questions SET accepted_answers = '["は", "よう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '葉' AND level = 8);
UPDATE questions SET accepted_answers = '["よう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '陽' AND level = 8);
UPDATE questions SET accepted_answers = '["さま", "よう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '様' AND level = 8);
UPDATE questions SET accepted_answers = '["お", "らく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '落' AND level = 8);
UPDATE questions SET accepted_answers = '["なが", "りゅう", "る"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '流' AND level = 8);
UPDATE questions SET accepted_answers = '["たび", "りょ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '旅' AND level = 8);
UPDATE questions SET accepted_answers = '["りょう"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '両' AND level = 8);
UPDATE questions SET accepted_answers = '["みどり", "りょく", "ろく"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '緑' AND level = 8);
UPDATE questions SET accepted_answers = '["れい", "らい"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '礼' AND level = 8);
UPDATE questions SET accepted_answers = '["れつ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '列' AND level = 8);
UPDATE questions SET accepted_answers = '["ね", "れん"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '練' AND level = 8);
UPDATE questions SET accepted_answers = '["じ", "ろ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '路' AND level = 8);
UPDATE questions SET accepted_answers = '["やわ", "わ"]' WHERE type = 'reading' AND kanji_id = (SELECT id FROM kanji WHERE character = '和' AND level = 8);