-- 9級（小学2年相当）漢字マスタ 160字
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('引', 9, 'イン', 'ひ(く)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('羽', 9, 'ウ', 'は・はね', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('雲', 9, 'ウン', 'くも', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('園', 9, 'エン', 'その', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('遠', 9, 'エン', 'とお(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('何', 9, 'カ', 'なに・なん', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('科', 9, 'カ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('夏', 9, 'カ', 'なつ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('家', 9, 'カ・ケ', 'いえ・や', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('歌', 9, 'カ', 'うた', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('画', 9, 'ガ・カク', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('回', 9, 'カイ', 'まわ(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('会', 9, 'カイ・エ', 'あ(う)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('海', 9, 'カイ', 'うみ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('絵', 9, 'カイ・エ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('外', 9, 'ガイ・ゲ', 'そと', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('角', 9, 'カク', 'かど・つの', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('楽', 9, 'ガク・ラク', 'たの(しい)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('活', 9, 'カツ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('間', 9, 'カン・ケン', 'あいだ・ま', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('丸', 9, 'ガン', 'まる', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('岩', 9, 'ガン', 'いわ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('顔', 9, 'ガン', 'かお', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('汽', 9, 'キ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('記', 9, 'キ', 'しる(す)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('帰', 9, 'キ', 'かえ(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('弓', 9, 'キュウ', 'ゆみ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('牛', 9, 'ギュウ', 'うし', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('魚', 9, 'ギョ', 'うお・さかな', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('京', 9, 'キョウ・ケイ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('強', 9, 'キョウ・ゴウ', 'つよ(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('教', 9, 'キョウ', 'おし(える)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('近', 9, 'キン', 'ちか(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('兄', 9, 'ケイ・キョウ', 'あに', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('形', 9, 'ケイ・ギョウ', 'かたち', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('計', 9, 'ケイ', 'はか(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('元', 9, 'ゲン・ガン', 'もと', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('言', 9, 'ゲン・ゴン', 'い(う)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('原', 9, 'ゲン', 'はら', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('戸', 9, 'コ', 'と', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('古', 9, 'コ', 'ふる(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('午', 9, 'ゴ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('後', 9, 'ゴ・コウ', 'のち・うし(ろ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('語', 9, 'ゴ', 'かた(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('工', 9, 'コウ・ク', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('公', 9, 'コウ', 'おおやけ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('広', 9, 'コウ', 'ひろ(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('交', 9, 'コウ', 'まじ(わる)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('光', 9, 'コウ', 'ひかり', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('考', 9, 'コウ', 'かんが(える)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('行', 9, 'コウ・ギョウ', 'い(く)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('高', 9, 'コウ', 'たか(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('黄', 9, 'コウ・オウ', 'き', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('合', 9, 'ゴウ・ガッ', 'あ(う)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('谷', 9, 'コク', 'たに', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('国', 9, 'コク', 'くに', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('黒', 9, 'コク', 'くろ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('今', 9, 'コン・キン', 'いま', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('才', 9, 'サイ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('細', 9, 'サイ', 'ほそ(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('作', 9, 'サク・サ', 'つく(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('算', 9, 'サン', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('止', 9, 'シ', 'と(まる)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('市', 9, 'シ', 'いち', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('矢', 9, 'シ', 'や', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('姉', 9, 'シ', 'あね', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('思', 9, 'シ', 'おも(う)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('紙', 9, 'シ', 'かみ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('寺', 9, 'ジ', 'てら', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('自', 9, 'ジ・シ', 'みずか(ら)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('時', 9, 'ジ', 'とき', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('室', 9, 'シツ', 'むろ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('社', 9, 'シャ', 'やしろ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('弱', 9, 'ジャク', 'よわ(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('首', 9, 'シュ', 'くび', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('秋', 9, 'シュウ', 'あき', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('週', 9, 'シュウ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('春', 9, 'シュン', 'はる', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('書', 9, 'ショ', 'か(く)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('少', 9, 'ショウ', 'すく(ない)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('場', 9, 'ジョウ', 'ば', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('色', 9, 'ショク・シキ', 'いろ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('食', 9, 'ショク', 'た(べる)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('心', 9, 'シン', 'こころ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('新', 9, 'シン', 'あたら(しい)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('親', 9, 'シン', 'おや', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('図', 9, 'ズ・ト', 'はか(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('数', 9, 'スウ・ス', 'かず', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('西', 9, 'セイ・サイ', 'にし', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('声', 9, 'セイ・ショウ', 'こえ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('星', 9, 'セイ・ショウ', 'ほし', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('晴', 9, 'セイ', 'は(れる)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('切', 9, 'セツ・サイ', 'き(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('雪', 9, 'セツ', 'ゆき', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('船', 9, 'セン', 'ふね', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('線', 9, 'セン', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('前', 9, 'ゼン', 'まえ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('組', 9, 'ソ', 'く(む)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('走', 9, 'ソウ', 'はし(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('多', 9, 'タ', 'おお(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('太', 9, 'タイ・タ', 'ふと(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('体', 9, 'タイ・テイ', 'からだ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('台', 9, 'ダイ・タイ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('地', 9, 'チ・ジ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('池', 9, 'チ', 'いけ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('知', 9, 'チ', 'し(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('茶', 9, 'チャ・サ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('昼', 9, 'チュウ', 'ひる', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('長', 9, 'チョウ', 'なが(い)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('鳥', 9, 'チョウ', 'とり', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('朝', 9, 'チョウ', 'あさ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('直', 9, 'チョク・ジキ', 'なお(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('通', 9, 'ツウ', 'とお(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('弟', 9, 'テイ・ダイ', 'おとうと', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('店', 9, 'テン', 'みせ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('点', 9, 'テン', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('電', 9, 'デン', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('刀', 9, 'トウ', 'かたな', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('冬', 9, 'トウ', 'ふゆ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('当', 9, 'トウ', 'あ(たる)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('東', 9, 'トウ', 'ひがし', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('答', 9, 'トウ', 'こた(える)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('頭', 9, 'トウ・ズ', 'あたま', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('同', 9, 'ドウ', 'おな(じ)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('道', 9, 'ドウ', 'みち', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('読', 9, 'ドク・トウ', 'よ(む)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('内', 9, 'ナイ・ダイ', 'うち', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('南', 9, 'ナン・ナ', 'みなみ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('肉', 9, 'ニク', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('馬', 9, 'バ', 'うま', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('売', 9, 'バイ', 'う(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('買', 9, 'バイ', 'か(う)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('麦', 9, 'バク', 'むぎ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('半', 9, 'ハン', 'なか(ば)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('番', 9, 'バン', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('父', 9, 'フ', 'ちち', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('風', 9, 'フウ・フ', 'かぜ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('分', 9, 'ブン・フン', 'わ(ける)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('聞', 9, 'ブン・モン', 'き(く)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('米', 9, 'ベイ・マイ', 'こめ', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('歩', 9, 'ホ・ブ', 'ある(く)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('母', 9, 'ボ', 'はは', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('方', 9, 'ホウ', 'かた', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('北', 9, 'ホク', 'きた', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('毎', 9, 'マイ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('妹', 9, 'マイ', 'いもうと', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('万', 9, 'マン・バン', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('明', 9, 'メイ・ミョウ', 'あか(るい)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('鳴', 9, 'メイ', 'な(く)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('毛', 9, 'モウ', 'け', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('門', 9, 'モン', 'かど', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('夜', 9, 'ヤ', 'よ・よる', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('野', 9, 'ヤ', 'の', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('友', 9, 'ユウ', 'とも', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('用', 9, 'ヨウ', 'もち(いる)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('曜', 9, 'ヨウ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('来', 9, 'ライ', 'く(る)', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('里', 9, 'リ', 'さと', NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('理', 9, 'リ', NULL, NULL, NULL, NULL);
INSERT INTO kanji (character, level, reading_on, reading_kun, radical, stroke_count, meaning) VALUES ('話', 9, 'ワ', 'はな(す)', NULL, NULL, NULL);

-- 9級 読み問題（各漢字1問、4択）
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '引' AND level = 9), 'reading', '「引」の読み方として正しいものはどれですか？', 'ひ', '["くび", "ひ", "ガ", "い"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '羽' AND level = 9), 'reading', '「羽」の読み方として正しいものはどれですか？', 'は', '["うま", "ふゆ", "ヨウ", "は"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '雲' AND level = 9), 'reading', '「雲」の読み方として正しいものはどれですか？', 'くも', '["まえ", "くも", "な", "はは"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '園' AND level = 9), 'reading', '「園」の読み方として正しいものはどれですか？', 'その', '["そと", "うお", "その", "ちか"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '遠' AND level = 9), 'reading', '「遠」の読み方として正しいものはどれですか？', 'とお', '["とお", "なか", "ニク", "のち"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '何' AND level = 9), 'reading', '「何」の読み方として正しいものはどれですか？', 'なに', '["な", "まじ", "く", "なに"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '科' AND level = 9), 'reading', '「科」の読み方として正しいものはどれですか？', 'カ', '["かた", "カ", "ひかり", "かど"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '夏' AND level = 9), 'reading', '「夏」の読み方として正しいものはどれですか？', 'なつ', '["うし", "バン", "かど", "なつ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '家' AND level = 9), 'reading', '「家」の読み方として正しいものはどれですか？', 'いえ', '["おとうと", "かぜ", "いえ", "おや"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '歌' AND level = 9), 'reading', '「歌」の読み方として正しいものはどれですか？', 'うた', '["の", "うた", "た", "うみ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '画' AND level = 9), 'reading', '「画」の読み方として正しいものはどれですか？', 'ガ', '["かた", "あいだ", "ヨウ", "ガ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '回' AND level = 9), 'reading', '「回」の読み方として正しいものはどれですか？', 'まわ', '["とお", "まわ", "ゆき", "ガ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '会' AND level = 9), 'reading', '「会」の読み方として正しいものはどれですか？', 'あ', '["あ", "キ", "あに", "ゆき"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '海' AND level = 9), 'reading', '「海」の読み方として正しいものはどれですか？', 'うみ', '["うお", "うみ", "き", "とり"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '絵' AND level = 9), 'reading', '「絵」の読み方として正しいものはどれですか？', 'カイ', '["はら", "ひ", "うお", "カイ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '外' AND level = 9), 'reading', '「外」の読み方として正しいものはどれですか？', 'そと', '["そと", "おし", "かず", "わ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '角' AND level = 9), 'reading', '「角」の読み方として正しいものはどれですか？', 'かど', '["にし", "おお", "キ", "かど"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '楽' AND level = 9), 'reading', '「楽」の読み方として正しいものはどれですか？', 'たの', '["たの", "い", "いけ", "な"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '活' AND level = 9), 'reading', '「活」の読み方として正しいものはどれですか？', 'カツ', '["あたら", "ダイ", "こえ", "カツ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '間' AND level = 9), 'reading', '「間」の読み方として正しいものはどれですか？', 'あいだ', '["つく", "かんが", "あいだ", "うみ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '丸' AND level = 9), 'reading', '「丸」の読み方として正しいものはどれですか？', 'まる', '["かんが", "くろ", "まる", "おお"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '岩' AND level = 9), 'reading', '「岩」の読み方として正しいものはどれですか？', 'いわ', '["ふゆ", "うま", "そと", "いわ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '顔' AND level = 9), 'reading', '「顔」の読み方として正しいものはどれですか？', 'かお', '["か", "ある", "さと", "かお"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '汽' AND level = 9), 'reading', '「汽」の読み方として正しいものはどれですか？', 'キ', '["いま", "キ", "てら", "かたち"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '記' AND level = 9), 'reading', '「記」の読み方として正しいものはどれですか？', 'しる', '["は", "うお", "しる", "や"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '帰' AND level = 9), 'reading', '「帰」の読み方として正しいものはどれですか？', 'かえ', '["き", "く", "とり", "かえ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '弓' AND level = 9), 'reading', '「弓」の読み方として正しいものはどれですか？', 'ゆみ', '["おや", "ゆみ", "く", "つよ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '牛' AND level = 9), 'reading', '「牛」の読み方として正しいものはどれですか？', 'うし', '["と", "な", "うし", "こめ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '魚' AND level = 9), 'reading', '「魚」の読み方として正しいものはどれですか？', 'うお', '["うお", "まわ", "キ", "みずか"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '京' AND level = 9), 'reading', '「京」の読み方として正しいものはどれですか？', 'キョウ', '["みち", "キョウ", "かず", "カツ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '強' AND level = 9), 'reading', '「強」の読み方として正しいものはどれですか？', 'つよ', '["つよ", "たに", "あたま", "くも"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '教' AND level = 9), 'reading', '「教」の読み方として正しいものはどれですか？', 'おし', '["おし", "はる", "みせ", "みち"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '近' AND level = 9), 'reading', '「近」の読み方として正しいものはどれですか？', 'ちか', '["はは", "ちか", "さと", "あさ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '兄' AND level = 9), 'reading', '「兄」の読み方として正しいものはどれですか？', 'あに', '["くに", "ふる", "リ", "あに"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '形' AND level = 9), 'reading', '「形」の読み方として正しいものはどれですか？', 'かたち', '["かんが", "かたち", "つく", "かお"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '計' AND level = 9), 'reading', '「計」の読み方として正しいものはどれですか？', 'はか', '["はか", "コウ", "おも", "うち"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '元' AND level = 9), 'reading', '「元」の読み方として正しいものはどれですか？', 'もと', '["もと", "かど", "にし", "ふゆ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '言' AND level = 9), 'reading', '「言」の読み方として正しいものはどれですか？', 'い', '["い", "キョウ", "うま", "はか"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '原' AND level = 9), 'reading', '「原」の読み方として正しいものはどれですか？', 'はら', '["はら", "かえ", "ふね", "ふと"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '戸' AND level = 9), 'reading', '「戸」の読み方として正しいものはどれですか？', 'と', '["と", "サン", "ひがし", "たに"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '古' AND level = 9), 'reading', '「古」の読み方として正しいものはどれですか？', 'ふる', '["とお", "ふる", "の", "と"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '午' AND level = 9), 'reading', '「午」の読み方として正しいものはどれですか？', 'ゴ', '["あに", "か", "ゴ", "まじ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '後' AND level = 9), 'reading', '「後」の読み方として正しいものはどれですか？', 'のち', '["のち", "よ", "う", "ひろ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '語' AND level = 9), 'reading', '「語」の読み方として正しいものはどれですか？', 'かた', '["ひかり", "ふと", "かた", "かぜ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '工' AND level = 9), 'reading', '「工」の読み方として正しいものはどれですか？', 'コウ', '["コウ", "かたち", "とお", "ゆみ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '公' AND level = 9), 'reading', '「公」の読み方として正しいものはどれですか？', 'おおやけ', '["と", "しる", "おおやけ", "あか"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '広' AND level = 9), 'reading', '「広」の読み方として正しいものはどれですか？', 'ひろ', '["な", "ひろ", "おとうと", "ふゆ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '交' AND level = 9), 'reading', '「交」の読み方として正しいものはどれですか？', 'まじ', '["よ", "みち", "くも", "まじ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '光' AND level = 9), 'reading', '「光」の読み方として正しいものはどれですか？', 'ひかり', '["テン", "ひかり", "あ", "かお"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '考' AND level = 9), 'reading', '「考」の読み方として正しいものはどれですか？', 'かんが', '["は", "き", "まじ", "かんが"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '行' AND level = 9), 'reading', '「行」の読み方として正しいものはどれですか？', 'い', '["ガ", "マイ", "い", "かお"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '高' AND level = 9), 'reading', '「高」の読み方として正しいものはどれですか？', 'たか', '["あたら", "あ", "き", "たか"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '黄' AND level = 9), 'reading', '「黄」の読み方として正しいものはどれですか？', 'き', '["いわ", "くも", "き", "そと"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '合' AND level = 9), 'reading', '「合」の読み方として正しいものはどれですか？', 'あ', '["くろ", "や", "あ", "ガ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '谷' AND level = 9), 'reading', '「谷」の読み方として正しいものはどれですか？', 'たに', '["かえ", "カ", "か", "たに"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '国' AND level = 9), 'reading', '「国」の読み方として正しいものはどれですか？', 'くに', '["やしろ", "ダイ", "くに", "かみ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '黒' AND level = 9), 'reading', '「黒」の読み方として正しいものはどれですか？', 'くろ', '["くろ", "うち", "あか", "チャ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '今' AND level = 9), 'reading', '「今」の読み方として正しいものはどれですか？', 'いま', '["いま", "まえ", "の", "ふゆ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '才' AND level = 9), 'reading', '「才」の読み方として正しいものはどれですか？', 'サイ', '["とお", "サイ", "バン", "よ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '細' AND level = 9), 'reading', '「細」の読み方として正しいものはどれですか？', 'ほそ', '["おおやけ", "うお", "け", "ほそ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '作' AND level = 9), 'reading', '「作」の読み方として正しいものはどれですか？', 'つく', '["おし", "あ", "ゆみ", "つく"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '算' AND level = 9), 'reading', '「算」の読み方として正しいものはどれですか？', 'サン', '["ちち", "サン", "からだ", "うま"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '止' AND level = 9), 'reading', '「止」の読み方として正しいものはどれですか？', 'と', '["た", "セン", "いち", "と"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '市' AND level = 9), 'reading', '「市」の読み方として正しいものはどれですか？', 'いち', '["あに", "バン", "くも", "いち"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '矢' AND level = 9), 'reading', '「矢」の読み方として正しいものはどれですか？', 'や', '["かど", "や", "うた", "なお"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '姉' AND level = 9), 'reading', '「姉」の読み方として正しいものはどれですか？', 'あね', '["か", "なお", "きた", "あね"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '思' AND level = 9), 'reading', '「思」の読み方として正しいものはどれですか？', 'おも', '["よわ", "とり", "まえ", "おも"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '紙' AND level = 9), 'reading', '「紙」の読み方として正しいものはどれですか？', 'かみ', '["さと", "なつ", "くも", "かみ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '寺' AND level = 9), 'reading', '「寺」の読み方として正しいものはどれですか？', 'てら', '["き", "とき", "てら", "や"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '自' AND level = 9), 'reading', '「自」の読み方として正しいものはどれですか？', 'みずか', '["いえ", "デン", "すく", "みずか"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '時' AND level = 9), 'reading', '「時」の読み方として正しいものはどれですか？', 'とき', '["みずか", "いろ", "か", "とき"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '室' AND level = 9), 'reading', '「室」の読み方として正しいものはどれですか？', 'むろ', '["むろ", "こめ", "くに", "おし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '社' AND level = 9), 'reading', '「社」の読み方として正しいものはどれですか？', 'やしろ', '["よわ", "テン", "マン", "やしろ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '弱' AND level = 9), 'reading', '「弱」の読み方として正しいものはどれですか？', 'よわ', '["よわ", "まじ", "うま", "うし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '首' AND level = 9), 'reading', '「首」の読み方として正しいものはどれですか？', 'くび', '["くび", "くろ", "おな", "コウ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '秋' AND level = 9), 'reading', '「秋」の読み方として正しいものはどれですか？', 'あき', '["いろ", "あき", "し", "ゆみ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '週' AND level = 9), 'reading', '「週」の読み方として正しいものはどれですか？', 'シュウ', '["シュウ", "はな", "か", "おとうと"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '春' AND level = 9), 'reading', '「春」の読み方として正しいものはどれですか？', 'はる', '["おお", "うた", "いけ", "はる"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '書' AND level = 9), 'reading', '「書」の読み方として正しいものはどれですか？', 'か', '["か", "かた", "ひかり", "くび"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '少' AND level = 9), 'reading', '「少」の読み方として正しいものはどれですか？', 'すく', '["なか", "すく", "と", "もち"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '場' AND level = 9), 'reading', '「場」の読み方として正しいものはどれですか？', 'ば', '["きた", "ば", "みずか", "いち"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '色' AND level = 9), 'reading', '「色」の読み方として正しいものはどれですか？', 'いろ', '["うま", "コウ", "いもうと", "いろ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '食' AND level = 9), 'reading', '「食」の読み方として正しいものはどれですか？', 'た', '["つよ", "かず", "た", "デン"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '心' AND level = 9), 'reading', '「心」の読み方として正しいものはどれですか？', 'こころ', '["てら", "なつ", "こころ", "キ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '新' AND level = 9), 'reading', '「新」の読み方として正しいものはどれですか？', 'あたら', '["のち", "まわ", "うま", "あたら"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '親' AND level = 9), 'reading', '「親」の読み方として正しいものはどれですか？', 'おや', '["かたち", "ある", "おや", "とも"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '図' AND level = 9), 'reading', '「図」の読み方として正しいものはどれですか？', 'はか', '["ふね", "はな", "デン", "はか"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '数' AND level = 9), 'reading', '「数」の読み方として正しいものはどれですか？', 'かず', '["たの", "うお", "かず", "の"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '西' AND level = 9), 'reading', '「西」の読み方として正しいものはどれですか？', 'にし', '["ほし", "ひる", "にし", "やしろ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '声' AND level = 9), 'reading', '「声」の読み方として正しいものはどれですか？', 'こえ', '["とも", "こえ", "はら", "ふゆ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '星' AND level = 9), 'reading', '「星」の読み方として正しいものはどれですか？', 'ほし', '["ひろ", "はら", "ほし", "と"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '晴' AND level = 9), 'reading', '「晴」の読み方として正しいものはどれですか？', 'は', '["とお", "は", "はか", "おお"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '切' AND level = 9), 'reading', '「切」の読み方として正しいものはどれですか？', 'き', '["い", "き", "と", "なお"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '雪' AND level = 9), 'reading', '「雪」の読み方として正しいものはどれですか？', 'ゆき', '["いろ", "サン", "ゆき", "サイ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '船' AND level = 9), 'reading', '「船」の読み方として正しいものはどれですか？', 'ふね', '["みち", "いろ", "ふね", "キョウ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '線' AND level = 9), 'reading', '「線」の読み方として正しいものはどれですか？', 'セン', '["くび", "ガ", "セン", "なつ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '前' AND level = 9), 'reading', '「前」の読み方として正しいものはどれですか？', 'まえ', '["かど", "くも", "ふと", "まえ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '組' AND level = 9), 'reading', '「組」の読み方として正しいものはどれですか？', 'く', '["カイ", "いえ", "く", "あたま"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '走' AND level = 9), 'reading', '「走」の読み方として正しいものはどれですか？', 'はし', '["カイ", "はし", "あに", "マン"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '多' AND level = 9), 'reading', '「多」の読み方として正しいものはどれですか？', 'おお', '["つよ", "ちち", "おお", "いち"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '太' AND level = 9), 'reading', '「太」の読み方として正しいものはどれですか？', 'ふと', '["ふと", "しる", "サイ", "こころ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '体' AND level = 9), 'reading', '「体」の読み方として正しいものはどれですか？', 'からだ', '["セン", "ほし", "かた", "からだ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '台' AND level = 9), 'reading', '「台」の読み方として正しいものはどれですか？', 'ダイ', '["ほし", "ダイ", "サン", "さと"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '地' AND level = 9), 'reading', '「地」の読み方として正しいものはどれですか？', 'チ', '["あ", "あ", "さと", "チ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '池' AND level = 9), 'reading', '「池」の読み方として正しいものはどれですか？', 'いけ', '["かたな", "いけ", "なお", "い"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '知' AND level = 9), 'reading', '「知」の読み方として正しいものはどれですか？', 'し', '["こえ", "のち", "し", "カ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '茶' AND level = 9), 'reading', '「茶」の読み方として正しいものはどれですか？', 'チャ', '["チ", "かた", "チャ", "こころ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '昼' AND level = 9), 'reading', '「昼」の読み方として正しいものはどれですか？', 'ひる', '["おおやけ", "チャ", "ひがし", "ひる"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '長' AND level = 9), 'reading', '「長」の読み方として正しいものはどれですか？', 'なが', '["なが", "まわ", "は", "し"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '鳥' AND level = 9), 'reading', '「鳥」の読み方として正しいものはどれですか？', 'とり', '["とり", "はか", "あたら", "みずか"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '朝' AND level = 9), 'reading', '「朝」の読み方として正しいものはどれですか？', 'あさ', '["あさ", "はは", "な", "リ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '直' AND level = 9), 'reading', '「直」の読み方として正しいものはどれですか？', 'なお', '["かえ", "なお", "よわ", "はか"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '通' AND level = 9), 'reading', '「通」の読み方として正しいものはどれですか？', 'とお', '["まえ", "とお", "こめ", "ひがし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '弟' AND level = 9), 'reading', '「弟」の読み方として正しいものはどれですか？', 'おとうと', '["いもうと", "ふる", "おとうと", "なつ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '店' AND level = 9), 'reading', '「店」の読み方として正しいものはどれですか？', 'みせ', '["うお", "みせ", "はる", "マン"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '点' AND level = 9), 'reading', '「点」の読み方として正しいものはどれですか？', 'テン', '["まえ", "テン", "くに", "からだ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '電' AND level = 9), 'reading', '「電」の読み方として正しいものはどれですか？', 'デン', '["とお", "はな", "デン", "はら"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '刀' AND level = 9), 'reading', '「刀」の読み方として正しいものはどれですか？', 'かたな', '["と", "きた", "おも", "かたな"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '冬' AND level = 9), 'reading', '「冬」の読み方として正しいものはどれですか？', 'ふゆ', '["すく", "ふゆ", "うち", "かみ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '当' AND level = 9), 'reading', '「当」の読み方として正しいものはどれですか？', 'あ', '["ふゆ", "いえ", "あ", "まえ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '東' AND level = 9), 'reading', '「東」の読み方として正しいものはどれですか？', 'ひがし', '["シュウ", "ひがし", "いわ", "ひ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '答' AND level = 9), 'reading', '「答」の読み方として正しいものはどれですか？', 'こた', '["むろ", "し", "き", "こた"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '頭' AND level = 9), 'reading', '「頭」の読み方として正しいものはどれですか？', 'あたま', '["く", "はか", "あたま", "さと"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '同' AND level = 9), 'reading', '「同」の読み方として正しいものはどれですか？', 'おな', '["ガ", "むろ", "おや", "おな"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '道' AND level = 9), 'reading', '「道」の読み方として正しいものはどれですか？', 'みち', '["みち", "おや", "さと", "いち"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '読' AND level = 9), 'reading', '「読」の読み方として正しいものはどれですか？', 'よ', '["チャ", "さと", "まえ", "よ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '内' AND level = 9), 'reading', '「内」の読み方として正しいものはどれですか？', 'うち', '["とり", "かみ", "つよ", "うち"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '南' AND level = 9), 'reading', '「南」の読み方として正しいものはどれですか？', 'みなみ', '["みなみ", "ば", "い", "チャ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '肉' AND level = 9), 'reading', '「肉」の読み方として正しいものはどれですか？', 'ニク', '["はら", "ニク", "つよ", "の"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '馬' AND level = 9), 'reading', '「馬」の読み方として正しいものはどれですか？', 'うま', '["カ", "コウ", "ほそ", "うま"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '売' AND level = 9), 'reading', '「売」の読み方として正しいものはどれですか？', 'う', '["う", "あ", "の", "その"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '買' AND level = 9), 'reading', '「買」の読み方として正しいものはどれですか？', 'か', '["サイ", "ば", "もと", "か"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '麦' AND level = 9), 'reading', '「麦」の読み方として正しいものはどれですか？', 'むぎ', '["まわ", "く", "むぎ", "か"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '半' AND level = 9), 'reading', '「半」の読み方として正しいものはどれですか？', 'なか', '["つく", "とき", "ふゆ", "なか"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '番' AND level = 9), 'reading', '「番」の読み方として正しいものはどれですか？', 'バン', '["ひがし", "くも", "バン", "キョウ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '父' AND level = 9), 'reading', '「父」の読み方として正しいものはどれですか？', 'ちち', '["はは", "ちち", "ば", "テン"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '風' AND level = 9), 'reading', '「風」の読み方として正しいものはどれですか？', 'かぜ', '["かぜ", "ニク", "やしろ", "うし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '分' AND level = 9), 'reading', '「分」の読み方として正しいものはどれですか？', 'わ', '["はる", "カツ", "わ", "く"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '聞' AND level = 9), 'reading', '「聞」の読み方として正しいものはどれですか？', 'き', '["は", "ふね", "き", "みち"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '米' AND level = 9), 'reading', '「米」の読み方として正しいものはどれですか？', 'こめ', '["こめ", "くも", "みせ", "あに"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '歩' AND level = 9), 'reading', '「歩」の読み方として正しいものはどれですか？', 'ある', '["ある", "ニク", "ほし", "はし"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '母' AND level = 9), 'reading', '「母」の読み方として正しいものはどれですか？', 'はは', '["あき", "はは", "いえ", "う"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '方' AND level = 9), 'reading', '「方」の読み方として正しいものはどれですか？', 'かた', '["よ", "なが", "け", "かた"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '北' AND level = 9), 'reading', '「北」の読み方として正しいものはどれですか？', 'きた', '["コウ", "きた", "みなみ", "はる"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '毎' AND level = 9), 'reading', '「毎」の読み方として正しいものはどれですか？', 'マイ', '["う", "マイ", "たに", "まる"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '妹' AND level = 9), 'reading', '「妹」の読み方として正しいものはどれですか？', 'いもうと', '["いもうと", "カツ", "なつ", "とも"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '万' AND level = 9), 'reading', '「万」の読み方として正しいものはどれですか？', 'マン', '["マン", "バン", "ゴ", "ふと"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '明' AND level = 9), 'reading', '「明」の読み方として正しいものはどれですか？', 'あか', '["あ", "なに", "その", "あか"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '鳴' AND level = 9), 'reading', '「鳴」の読み方として正しいものはどれですか？', 'な', '["バン", "いわ", "いもうと", "な"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '毛' AND level = 9), 'reading', '「毛」の読み方として正しいものはどれですか？', 'け', '["ゆみ", "むぎ", "まじ", "け"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '門' AND level = 9), 'reading', '「門」の読み方として正しいものはどれですか？', 'かど', '["あき", "たか", "マン", "かど"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '夜' AND level = 9), 'reading', '「夜」の読み方として正しいものはどれですか？', 'よ', '["たの", "よ", "むぎ", "もち"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '野' AND level = 9), 'reading', '「野」の読み方として正しいものはどれですか？', 'の', '["とお", "あか", "は", "の"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '友' AND level = 9), 'reading', '「友」の読み方として正しいものはどれですか？', 'とも', '["かど", "いわ", "おし", "とも"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '用' AND level = 9), 'reading', '「用」の読み方として正しいものはどれですか？', 'もち', '["サン", "はな", "うお", "もち"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '曜' AND level = 9), 'reading', '「曜」の読み方として正しいものはどれですか？', 'ヨウ', '["ヨウ", "うみ", "よわ", "ゴ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '来' AND level = 9), 'reading', '「来」の読み方として正しいものはどれですか？', 'く', '["く", "ひる", "いわ", "たに"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '里' AND level = 9), 'reading', '「里」の読み方として正しいものはどれですか？', 'さと', '["さと", "ゴ", "こめ", "わ"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '理' AND level = 9), 'reading', '「理」の読み方として正しいものはどれですか？', 'リ', '["しる", "リ", "にし", "とき"]');
INSERT INTO questions (kanji_id, type, prompt, correct_answer, choices) VALUES ((SELECT id FROM kanji WHERE character = '話' AND level = 9), 'reading', '「話」の読み方として正しいものはどれですか？', 'はな', '["ダイ", "むろ", "はな", "とき"]');
